# latexmk configuration for the MISSY technical documentation.
#
# ENGINE: XeLaTeX, not LuaLaTeX.  This is not a preference.  The preamble loads
# ucharclasses, which ships in texmf-dist/tex/xelatex/ and is XeTeX-only: it
# hooks XeTeX's interchar-class mechanism to switch to the CJK family when a
# CJK block is met.  Under LuaLaTeX the package is simply not found, so
# $pdf_mode = 4 cannot build this document.  $pdf_mode = 5 is XeLaTeX.
$pdf_mode = 5;
$postscript_mode = $dvi_mode = 0;

# -no-shell-escape: every listing is embedded, nothing is generated by running a
# program, and the document must build on a machine that forbids shell escape.
$xelatex = 'xelatex -no-shell-escape -interaction=nonstopmode -halt-on-error %O %S';

# The appendices bind in ~5,300 pages of atlas and annex, so a pass is slow and
# the reference/TOC loop needs room to settle.  The default of 5 is enough for
# this document; raise it only if latexmk says it ran out.
$max_repeat = 7;

# Intermediate files latexmk -c removes.  main.pdf is NOT in this list.
$clean_ext = 'synctex.gz fls fdb_latexmk aux log toc lof lot out bbl blg run.xml';

# The PDFs bound in by appendices K and L live here; they are inputs, so a
# changed volume triggers a rebuild.
push @generated_exts, 'synctex.gz';
