const ZH_TERMS={
  "qPCR raw values, open formats, quality control and forensics — LightCycler 480 · QuantStudio 3/5":"qPCR 原始数据、开放格式、质量控制与取证分析 — LightCycler 480 · QuantStudio 3/5",
  "Reads a finished LightCycler 480 .ixo or QuantStudio 3/5 .eds experiment, hands you the numbers the instrument stored, draws them, reviews them and writes them in formats that open-source tools read directly. Nothing is uploaded; everything runs in this page.":"读取已完成的 LightCycler 480 .ixo 或 QuantStudio 3/5 .eds 实验，校验文件容器是否完整，呈现仪器保存的数值，绘图、审核，并导出为开源工具可直接读取的格式。数据不会上传，所有处理均在本页面中完成。",
  "Drop one or more LightCycler 480 .ixo files, QuantStudio .eds files or .edt templates, or a .zip containing them. Several runs — from either instrument — can be loaded at once; the Quality review tab compares them.":"拖入一个或多个 LightCycler 480 .ixo 文件、QuantStudio .eds 文件或 .edt 模板，也可拖入包含这些文件的 .zip。可同时加载两种仪器的多个运行，并在“质量审核”中进行比较。",
  "Drop .ixo, .eds, .edt or .zip here":"将 .ixo、.eds、.edt 或 .zip 拖到这里",
  "the curve-based exports need an .ixo or .eds file.":"基于曲线的导出需要 .ixo 或 .eds 文件。",
  "Nothing here is recomputed. For .ixo files Cq is the stored crossing point, concentration the stored CalcConc and the call the instrument's own. For .eds files Cq is the stored Ct, the call follows the stored amplification status, and flags, ΔCt, ΔΔCt and RQ are the analysis software's own.":"此处不重新计算任何数值。对于 .ixo 文件，Cq 为保存的交叉点，浓度为保存的 CalcConc，判定为仪器自身结果。对于 .eds 文件，Cq 为保存的 Ct，判定依据保存的扩增状态，标记、ΔCt、ΔΔCt 与 RQ 均为分析软件自身的结果。",
  "Download relative quantification (CSV)":"下载相对定量结果（CSV）",
  "Relative quantification (stored)":"相对定量（保存值）",
  "Pseudonymise sample names in downloads (controls keep their names; the original .eds path is withheld)":"下载时对样品名称进行假名化（对照保留原名；不输出 .eds 原始路径）",
  "Download pseudonym mapping (CSV)":"下载假名对照表（CSV）",
  "The mapping stays on this page unless you download it. Keep it with the laboratory records, not with published data.":"对照表仅保留在本页面中，除非您主动下载。请与实验室记录一同保存，不要随公开数据发布。",
  "LightCycler 480: raw fluorescence as stored in the AcquisitionStore, with no smoothing and no baseline subtraction. QuantStudio: the stored Rn by default, or the stored ΔRn (with its threshold), the multicomponent signal per dye, or the raw filter-set data. Controls are drawn over ordinary samples so they stay visible.":"LightCycler 480：AcquisitionStore 中保存的原始荧光，不做平滑与基线扣除。QuantStudio：默认显示保存的 Rn，也可显示保存的 ΔRn（含阈值）、各染料的多组分信号或原始滤光片组数据。对照曲线绘制在普通样品之上，便于查看。",
  "Signal":"信号","Stored curve (raw / Rn)":"保存的曲线（原始 / Rn）","ΔRn with threshold":"ΔRn 与阈值",
  "Multicomponent (per dye)":"多组分（按染料）","Raw filter-set data":"原始滤光片组数据",
  "All samples":"全部样品","Target / dye / filter":"靶标 / 染料 / 滤光片","Show threshold":"显示阈值",
  "Run metadata, thermal program, detection channels, analysis objects and the instrument's own replicate statistics — plus, for QuantStudio files, calibrations, software modules, target settings, flag rules, the instrument log and the block temperature trace — decoded verbatim from the file.":"运行元数据、容器完整性、热循环程序、检测通道、分析对象及仪器自身的重复统计；QuantStudio 文件另含校准、软件模块、靶标设置、标记规则、仪器日志与模块温度曲线，均按原样从文件解码。",
  "Load one or more .ixo or .eds experiments to use this sheet.":"请先加载一个或多个 .ixo 或 .eds 实验。",
  "Instrument family":"仪器系列","Container integrity":"容器完整性","Amp status":"扩增状态","Flags":"标记",
  "ΔCq":"ΔCq","RQ":"RQ","Reference":"参照","Target Cq":"靶标 Cq","Reference Cq":"参照 Cq","ΔCq mean":"ΔCq 均值",
  "ΔCq SE":"ΔCq 标准误","ΔΔCq":"ΔΔCq","RQ / ratio":"RQ / 比值","Min":"最小值","Max":"最大值","n":"n",
  "Forensic log (CSV)":"容器完整性与取证日志（CSV）",
  "One row per run (counts, status) and one per finding: controls, flags, replicate spread, Ct traceability, calibrations and instrument log.":"每个运行一行（校验值、计数、状态），每条发现一行：容器校验、对照、标记、重复孔离散度、Ct 可追溯性、校准与仪器日志。",
  "QuantStudio export layout (TXT)":"QuantStudio 导出格式（TXT）",
  "Header, Sample Setup, Raw Data, Amplification Data, Multicomponent Data and Results, tab-delimited, following the export specification of the QuantStudio command-line guide (MAN0010409, chapter 3). For LIS/LIMS parsers that expect that layout.":"包含文件头、样品设置、原始数据、扩增数据、多组分数据与结果，制表符分隔，遵循 QuantStudio 命令行指南（MAN0010409 第 3 章）的导出规范，供期望该格式的 LIS/LIMS 解析程序使用。",
  "Relative quantification (CSV)":"相对定量（CSV）",
  "Stored relative-quantification results: ΔΔCt summaries with RQ and confidence limits from QuantStudio, pairing ratios from LightCycler.":"保存的相对定量结果：QuantStudio 的 ΔΔCt 汇总（含 RQ 及置信限），以及 LightCycler 的配对比值。",
  "Multicomponent and raw filter data (CSV)":"多组分与原始滤光片数据（CSV）",
  "QuantStudio only: per-dye multicomponent signal and every filter-set reading, one row per named well and cycle — the data under the stored Rn.":"仅限 QuantStudio：各染料的多组分信号及全部滤光片组读数，每个已命名孔位、每个循环一行，即保存的 Rn 所依据的数据。",
  "container checksum matches":"容器校验值一致","container checksum MISMATCH":"容器校验值不一致","no container checksum":"无容器校验值","not checked":"未检查",
  "Integrity":"完整性","Calibration":"校准","Replicates":"重复孔","Relative quantification":"相对定量","Ct traceability":"Ct 可追溯性",
  "Instrument log":"仪器日志","Plate setup":"板设置","Run state":"运行状态","Endogenous control":"内参","Stored Ct":"保存的 Ct",
  "Container checksum matches the object stream":"容器校验值与对象流一致",
  "Container checksum does not match — the file was changed after the software sealed it":"容器校验值不一致 - 文件在软件封存后被修改",
  "No container checksum could be verified":"无法验证容器校验值",
  "ZIP CRC-32 failed":"ZIP CRC-32 校验失败","Tamper MD5 matches the stored value":"Tamper MD5 与保存值一致",
  "Tamper MD5 does not match — the file was changed after the software sealed it":"Tamper MD5 不一致 - 文件在软件封存后被修改",
  "No Tamper record in the container":"容器中没有 Tamper 记录","expected for a template":"模板文件属正常情况",
  "Template or unrun experiment":"模板或未运行的实验","Final analysis is not marked complete":"最终分析未标记为完成",
  "NTC wells are identified by name only":"NTC 孔位仅由名称识别",
  "their task is UNKNOWN in the plate setup, so the instrument's AMPNC rule cannot fire on them":"其在板设置中的任务为 UNKNOWN，因此仪器的 AMPNC 规则无法对其生效",
  "QuantStudio experiment decoded":"QuantStudio 实验已解码","Well without a sample name carries a rising curve":"无样品名称的孔位出现上升曲线",
  "messages.log is missing from a completed run":"已完成的运行缺少 messages.log",
  "Log start and experiment start differ by more than 2 minutes":"日志开始时间与实验开始时间相差超过 2 分钟",
  "read, but left out of the result rows":"已读取，但未列入结果行","shifts above 3 cycles are marked for review":"偏移超过 3 个循环时标记审核",
  "Block and cover temperature during the run":"运行期间的模块与热盖温度","sample zones (mean)":"样品区（均值）",
  "heated cover":"热盖","zone spread (max − min)":"区间温差（最大 − 最小）","Minutes from the first log record":"自首条日志记录起的分钟数",
  "Calibrations":"校准","Target settings":"靶标设置","Analysis settings":"分析设置","Flag rules":"标记规则",
  "Software modules":"软件模块","Instrument log summary":"仪器日志摘要","Run events":"运行事件",
  "Errors and warnings in the instrument log":"仪器日志中的错误与警告","Archive entries":"压缩包条目",
  "ΔRn (stored)":"ΔRn（保存值）","Multicomponent signal":"多组分信号","Raw filter-set fluorescence":"原始滤光片组荧光",
  "Rn (stored)":"Rn（保存值）","Raw fluorescence (log scale)":"原始荧光（对数坐标）","ΔRn (stored) (log scale)":"ΔRn（保存值，对数坐标）",
  "Rn (stored) (log scale)":"Rn（保存值，对数坐标）","Multicomponent signal (log scale)":"多组分信号（对数坐标）",
  "Raw filter-set fluorescence (log scale)":"原始滤光片组荧光（对数坐标）",
  "Hover a line to identify it.":"将鼠标悬停在曲线上可查看其信息。",
  "The CSV contains every cycle of every selected curve, including curves hidden by overlap in the chart. Hover a line to identify it.":"CSV 包含每条已选曲线的全部循环数据，包括图中因重叠而不可见的曲线。将鼠标悬停在曲线上可查看其信息。",
  "QuantStudio export workbook (XLSX)":"QuantStudio 导出工作簿（XLSX）",
  "The same sheets, columns and row order as the QuantStudio software's Excel export (Sample Setup, Raw Data, Amplification Data, Multicomponent Data, analysis summaries, Results, Reagent Information), rebuilt from the .eds using the export configuration saved inside it.":"与 QuantStudio 软件 Excel 导出相同的工作表、列与行顺序（样品设置、原始数据、扩增数据、多组分数据、分析汇总、结果、试剂信息），依据 .eds 内保存的导出配置重建。",
  "Header plus Sample Setup, Raw Data, Amplification Data, Multicomponent Data, analysis summaries and Results as tab-delimited sections (MAN0010409, chapter 3), with the columns and row order of the software's own export. For LIS/LIMS parsers that expect that layout.":"文件头及样品设置、原始数据、扩增数据、多组分数据、分析汇总与结果，以制表符分隔的分节形式输出（MAN0010409 第 3 章），列与行顺序与软件自身导出一致，供期望该格式的 LIS/LIMS 解析程序使用。",
  "Provenance":"来源","Standard curve":"标准曲线",
  "Standard curves":"标准曲线","Provenance recorded in the file":"文件中记录的来源信息","Per-well baselines":"各孔基线",
  "Export configuration saved in the file":"文件中保存的导出配置",
  "around":"约在",
  "All control charts, all instruments (ZIP)":"所有仪器的全部控制图（ZIP）",
  "with PNG":"含 PNG",
  "Preparing the charts":"正在生成图表",
  "ZIP ready":"ZIP 已生成",
  "files":"个文件",
  "This graph uses the QuantStudio instrument log. For a LightCycler run choose “Block temperature trace (LightCycler temperature log)”.":"此图使用 QuantStudio 仪器日志。LightCycler 运行请选择“加热块温度曲线（LightCycler 温度日志）”。",
  "Transition time A → B °C":"转换时间 A → B °C",
  "LC TemperatureLog · QS log sample temperature · run program":"LC 温度日志 · QS 日志样品温度 · 运行程序",
  "Seconds the block needs to go from one programmed temperature to the next (e.g. 95 → 60 °C): from leaving ±0.5 °C of the start temperature until first within ±0.5 °C of the target, median over all cycles of the run. One chart per transition of the program. Includes ramp and overshoot, so it shows how much of every cycle is spent moving instead of holding.":"加热块从一个设定温度到下一个设定温度（如 95 → 60 °C）所需的秒数：从离开起始温度 ±0.5 °C 到首次进入目标温度 ±0.5 °C，取运行中所有循环的中位数。程序中每种转换各一张图。包含升降温和过冲，因此显示每个循环中用于移动而非保持的时间。",
  "Compare a transition only with itself and the same program. A cooling transition that lengthens while heating transitions stay flat points to heat removal (fans, filters, heat sink); all transitions lengthening together points to the Peltier elements or the room.":"只将同一转换在相同程序下比较。降温转换变长而升温转换稳定，指向散热（风扇、过滤网、散热器）；所有转换同时变长，指向 Peltier 元件或室温。",
  "Fit the wear line on":"磨损趋势线拟合范围",
  "All runs since the baseline (updates with every run)":"基线以来的所有运行（每次运行更新）",
  "Only the baseline runs (Phase I, fixed)":"仅基线运行（第一阶段，固定）",
  "Peak heating rate (2-s window)":"峰值加热速率（2 秒窗口）",
  "Peak cooling rate (2-s window)":"峰值冷却速率（2 秒窗口）",
  "Lamp reference channel (stability)":"灯参考通道（稳定性）",
  "Protocol":"程序",
  "All protocols":"所有程序",
  "Baseline starts on (after a repair or service)":"基线起始日期（维修或保养后）",
  "new baseline":"新基线",
  "no runs since the new baseline date":"新基线日期后没有运行",
  "1 · Hardware":"1 · 硬件",
  "thermal, optics, mechanics — predictive maintenance":"热、光学、机械 — 预测性维护",
  "2 · Software":"2 · 软件",
  "embedded computer, analysis software, data integrity":"嵌入式计算机、分析软件、数据完整性",
  "3 · Method":"3 · 方法",
  "reagents, probes, assay behaviour":"试剂、探针、检测表现",
  "4 · Operator":"4 · 操作人员",
  "pipetting skill, consistency, forensic":"移液技能、一致性、取证",
  "Heating rate (10–90 %)":"加热速率（10–90 %）",
  "How fast the Peltier elements heat the block. Median of every heating step in the run.":"帕尔帖元件加热模块的速度。取本次运行所有升温步骤的中位数。",
  "A slow fall over months is Peltier or thermal-interface ageing; the fitted line gives a conditional limit-crossing estimate, not a failure date. A single low run points to the plate or a blocked vent that day.":"数月内缓慢下降表明帕尔帖元件或导热界面老化；趋势线可预测何时低于下限。单次偏低多与当天的板或通风口堵塞有关。",
  "Cooling rate (10–90 %)":"冷却速率（10–90 %）",
  "How well the heat sink and fans remove heat. Median of every cooling step.":"散热器和风扇带走热量的能力。取所有降温步骤的中位数。",
  "Falling cooling with stable heating = clogged fan filter or failing fan (clean the filters, check fans) before Peltier replacement.":"加热正常而冷却下降 = 风扇滤网堵塞或风扇故障（先清洁滤网、检查风扇），再考虑更换帕尔帖元件。",
  "Overshoot at the denaturation step":"变性步骤的过冲",
  "Block temperature beyond the setpoint before it settles. The LC480 overshoots 4–6 °C by design, identically every cycle.":"模块温度在稳定前超过设定值的幅度。LC480 按设计每个循环都过冲 4–6 °C，且保持一致。",
  "Watch for change, not size: a CUSUM drifting up or down means the controller or the temperature sensor has changed.":"关注变化而非大小：CUSUM 向上或向下漂移表示控制器或温度传感器发生了变化。",
  "Settling time at the denaturation step":"变性步骤的稳定时间",
  "Seconds from the 90 % point until the block stays within ±0.5 °C of the setpoint.":"从 90 % 点到模块稳定在设定值 ±0.5 °C 内所需的秒数。",
  "Longer settling with a normal ramp rate points to control tuning or sensor lag.":"升降温速率正常而稳定时间变长，提示控制参数或传感器滞后问题。",
  "Temperature at the moment of reading":"读数时的温度",
  "°C from setpoint":"与设定值的偏差 °C",
  "Offset (X̄) and stability (S) of the block while the camera reads, one subgroup per run.":"相机读数时模块温度的偏差（X̄）和稳定性（S），每次运行为一个子组。",
  "X̄ drifting away from its usual offset = temperature calibration drift (verify with a temperature plate). S rising = unstable control.":"X̄ 偏离其通常偏差 = 温度校准漂移（用温度验证板确认）。S 上升 = 控制不稳定。",
  "Block zone uniformity (95th percentile)":"模块分区均匀性（第 95 百分位）",
  "Difference between the warmest and coolest of the six zones, 95th percentile over the run.":"六个分区中最热与最冷之差，取整个运行的第 95 百分位。",
  "An EWMA creeping up means one zone is losing its match; look at the Temperature graph to find which.":"EWMA 缓慢上升表示某一分区逐渐失配；请在温度图中查找是哪一个分区。",
  "Heat-sink maximum":"散热器最高温度",
  "Highest heat-sink temperature during the run.":"运行期间散热器的最高温度。",
  "Rising over time with the same protocol = cooling capacity dropping (fans, dust, room temperature).":"同一程序下逐渐升高 = 散热能力下降（风扇、灰尘、室温）。",
  "Heated cover temperature":"热盖温度",
  "Median cover temperature during the run (setpoint 105 °C).":"运行期间热盖温度的中位数（设定值 105 °C）。",
  "Below the setpoint = cover heater fault; condensation and evaporation follow.":"低于设定值 = 热盖加热器故障，随之出现冷凝和蒸发。",
  "Xenon lamp intensity (reference channel)":"氙灯强度（参考通道）",
  "reference counts":"参考计数",
  "The instrument measures the lamp through a reference channel. The first reading of each run tracks lamp ageing (manual: warning at 50 %, lifetime ≈ 500 h).":"仪器通过参考通道测量灯的强度。每次运行的首次读数反映灯的老化（手册：50 % 时报警，寿命约 500 小时）。",
  "The fitted line predicts when 50 % of the starting value is reached — order the lamp before that. A point far below the line is a sudden lamp or light-guide fault.":"拟合线预测何时降至起始值的 50 % — 请在此之前订购新灯。明显低于拟合线的点表示灯或光导突发故障。",
  "Lamp drift within a run":"运行内的灯强度漂移",
  "% change in the run":"运行内变化 %",
  "How much the lamp intensity changes during one run.":"一次运行中灯强度的变化幅度。",
  "Growing drift is typical of a lamp near the end of its life.":"漂移逐渐增大是灯接近寿命终点的典型表现。",
  "LED drive current":"LED 驱动电流",
  "current (as logged)":"电流（日志原值）",
  "Median LED current during the run.":"运行期间 LED 电流的中位数。",
  "The instrument raises current to keep light output: a rising trend is LED ageing; the line predicts when it reaches the limit you set.":"仪器会提高电流以维持光输出：上升趋势表示 LED 老化；拟合线可预测何时达到您设定的限值。",
  "LED junction temperature (maximum)":"LED 结温（最高值）",
  "Hottest LED junction temperature in the run.":"运行中 LED 结温的最高值。",
  "Higher than usual = LED cooling problem; LEDs age faster when hot.":"高于平常 = LED 散热问题；LED 在高温下老化更快。",
  "Automatic integration time / exposure":"自动积分时间 / 曝光时间",
  "Both instruments lengthen exposure automatically when the signal is weak.":"信号较弱时，两种仪器都会自动延长曝光时间。",
  "A slow rise is compatible with weaker signal; verify matched controls and optical configuration before attributing ageing (compare with B-H8/B-H10); a jump after a reagent change points to the method instead.":"缓慢上升证实光源老化（与 B-H8/B-H10 对照）；更换试剂后出现跳变则指向方法问题。",
  "Saturated well images":"饱和孔图像",
  "share of well images":"孔图像比例",
  "Share of well images with at least one saturated pixel.":"至少含一个饱和像素的孔图像比例。",
  "A rise = exposure logic or camera fault, or overloaded samples; values above zero make the curve plateau unreliable.":"上升 = 曝光逻辑或相机故障，或样品过载；大于零时曲线平台不可靠。",
  "Uniformity calibration: edge-to-centre ratio":"均匀性校准：边缘与中心之比",
  "edge / centre":"边缘 / 中心",
  "Changes only when the instrument is recalibrated.":"仅在仪器重新校准时变化。",
  "A step at a recalibration shows how much the optics changed; a large step deserves a service question.":"重新校准时的阶跃反映光学系统的变化程度；阶跃较大时应咨询维修服务。",
  "Background calibration: mean offset":"背景校准：平均偏移",
  "counts":"计数",
  "Mean absolute background offset of the last background calibration.":"最近一次背景校准的平均绝对背景偏移。",
  "Rising between calibrations = contamination of the block or optics.":"两次校准之间上升 = 模块或光学系统受到污染。",
  "Well-position (ROI) calibration: spot diameter":"孔位（ROI）校准：光斑直径",
  "pixels":"像素",
  "Mean spot diameter from the ROI calibration.":"ROI 校准得到的平均光斑直径。",
  "A change means the optical alignment moved.":"发生变化表示光学对准发生了移动。",
  "Filter-wheel move time":"滤光轮移动时间",
  "Median time of a filter-wheel move.":"滤光轮单次移动时间的中位数。",
  "Slower moves = motor or bearing wear.":"移动变慢 = 电机或轴承磨损。",
  "Filter-wheel moves slower than 500 ms":"滤光轮移动慢于 500 ms",
  "share of moves":"移动比例",
  "Share of moves longer than 500 ms (normal ≈ 300 ms).":"移动时间超过 500 ms 的比例（正常约 300 ms）。",
  "Occasional stalls come before a failure; any upward trend is worth a service call.":"偶发卡顿往往先于故障出现；任何上升趋势都值得联系维修。",
  "Filter-wheel position offset":"滤光轮位置偏移",
  "encoder counts":"编码器计数",
  "Encoder offset after each move; constant for a healthy wheel.":"每次移动后的编码器偏移；轮子正常时保持恒定。",
  "Any step = the wheel slipped, was re-homed or serviced.":"任何阶跃 = 轮子打滑、重新归零或经过维修。",
  "Camera readout time beyond the exposure":"超出曝光时间的相机读出时间",
  "About 0.5 s per image; one subgroup = all images of the run.":"每幅图像约 0.5 s；一个子组 = 本次运行的全部图像。",
  "A jump = camera or its interface; a slow rise = controller slowing (compare with software charts).":"跳变 = 相机或其接口问题；缓慢上升 = 控制器变慢（与软件图表对照）。",
  "Channel switch time":"通道切换时间",
  "Time between the channels of one reading, net of integration (≈ 1.0–1.4 s; filter switch < 0.65 s by the manual).":"一次读数中各通道之间的时间，扣除积分时间（约 1.0–1.4 s；手册规定滤光片切换 < 0.65 s）。",
  "Rising = filter wheels or camera readout slowing.":"上升 = 滤光轮或相机读出变慢。",
  "Heated cover lowering time":"热盖下降时间",
  "Motorised cover pressing onto the plate (≈ 10 s).":"电动热盖压到板上的时间（约 10 s）。",
  "Getting slower = motor or linkage wear, or plates/seals that are too tall.":"变慢 = 电机或连杆磨损，或板/封膜过高。",
  "Heated cover raising time":"热盖抬起时间",
  "Cover lifting off the plate (≈ 5.4 s).":"热盖从板上抬起的时间（约 5.4 s）。",
  "As B-H18.":"同 B-H18。",
  "Background fluorescence per channel":"各通道背景荧光",
  "fluorescence":"荧光",
  "Median background of all wells, per channel.":"各通道所有孔背景的中位数。",
  "Slow decline = light source ageing; a raised run = plate, seal or contamination.":"缓慢下降 = 光源老化；某次运行偏高 = 板、封膜或污染。",
  "End-point fluorescence per channel":"各通道终点荧光",
  "Median end-point of all wells, per channel.":"各通道所有孔终点荧光的中位数。",
  "Moves together with B-H8/B-H10 when optics age; alone it points to the method (probe) — see M-group.":"在光学老化时与 B-H8/B-H10 一起变化；单独变化则指向方法（探针）— 见方法组。",
  "Run duration":"运行时长",
  "minutes":"分钟",
  "Only comparable between runs of the same protocol.":"仅在相同程序的运行之间可比。",
  "A much shorter or longer run with the same protocol = aborted, paused or held run.":"相同程序下运行时间明显偏短或偏长 = 运行中止、暂停或等待。",
  "Reply time to the PC software":"对 PC 软件的响应时间",
  "ms (95th pct)":"ms（第 95 百分位）",
  "How fast the embedded computer answers commands.":"嵌入式计算机响应命令的速度。",
  "Rising = controller overloaded or network problem.":"上升 = 控制器过载或网络问题。",
  "Once-per-second timer lateness":"每秒定时器延迟",
  "How late the 1-s housekeeping timer fires.":"1 秒周期的维护定时器触发延迟了多少。",
  "Rising = the embedded CPU is saturated (mostly while imaging).":"上升 = 嵌入式 CPU 饱和（多发生在成像时）。",
  "Scheduler falling behind":"调度器落后",
  "events per run hour":"每运行小时事件数",
  "How often the task scheduler had to catch up, per hour of run.":"任务调度器需要追赶进度的频率（每运行小时）。",
  "A u-chart above its limit = the internal computer is overloaded.":"u 图超出限值 = 内部计算机过载。",
  "Image → processing delay":"图像 → 处理延迟",
  "Time from the last image to the start of its processing.":"从最后一幅图像到开始处理的时间。",
  "Rising = storage or CPU slowing; one long delay is a single stall.":"上升 = 存储或 CPU 变慢；单次长延迟为一次卡顿。",
  "Image analysis time":"图像分析时间",
  "The software's own processing time per image.":"软件自身报告的每幅图像处理时间。",
  "A step after an update = different firmware behaviour (see version markers).":"更新后出现阶跃 = 固件行为改变（见版本标记）。",
  "Run-time prediction error":"运行时间预测误差",
  "Actual minus predicted run time.":"实际运行时间减去预测时间。",
  "Creeping up = actions take longer than the firmware expects.":"逐渐上升 = 各项操作耗时超过固件预期。",
  "Data hand-off time":"数据交接时间",
  "Minutes from run end until the data were packed for the PC.":"从运行结束到数据打包交给 PC 的分钟数。",
  "Long = network or PC problem, or a manual delay.":"过长 = 网络或 PC 问题，或人为延迟。",
  "Command errors in the instrument log":"仪器日志中的命令错误",
  "errors":"错误",
  "Count of command errors per run.":"每次运行的命令错误数。",
  "New or more errors = firmware or configuration change.":"出现新错误或错误增多 = 固件或配置变化。",
  "Cycle-timing regularity":"循环计时规律性",
  "Standard deviation of the cycle period within a run.":"运行内循环周期的标准差。",
  "Larger = scheduling problems in the instrument.":"变大 = 仪器内部调度问题。",
  "Temperature-log intervals over 500 ms":"温度日志间隔超过 500 ms",
  "share of intervals":"间隔比例",
  "Regularity of the control-loop logging.":"控制回路记录的规律性。",
  "Any rise = controller overload.":"任何上升 = 控制器过载。",
  "Invalid fluorescence readings":"无效荧光读数",
  "share of readings":"读数比例",
  "Readings the instrument marked invalid.":"仪器标记为无效的读数。",
  "Above zero = acquisition fault.":"大于零 = 采集故障。",
  "Stored Ct not reproducible (> 0.2)":"保存的 Ct 无法复现（> 0.2）",
  "share of wells":"孔比例",
  "Wells whose stored Ct differs from the recalculation.":"保存的 Ct 与重新计算值不同的孔。",
  "Non-zero requires checking algorithm, precision, stored settings and provenance; it does not establish post-analysis editing.":"不为零 = 分析后设置或数据被修改（需取证跟进）。",
  "Run end → last change":"运行结束 → 最后修改",
  "log10 hours":"log10 小时",
  "Processing delay on a log scale (0 = 1 h, 1 = 10 h, 2 = 100 h).":"对数刻度的处理延迟（0 = 1 小时，1 = 10 小时，2 = 100 小时）。",
  "Points above the limit are late edits; cross-check with the operator group.":"高于限值的点为延迟编辑；请与操作人员组图表交叉核对。",
  "Forensic findings per run":"每次运行的取证发现",
  "findings":"发现",
  "Count of review and error findings for the run.":"本次运行的待审核和错误发现数量。",
  "A run above the limit needs a closer look in the forensic log.":"高于限值的运行需要在取证日志中仔细查看。",
  "Positive control Cq (Levey-Jennings)":"阳性对照 Cq（Levey-Jennings）",
  "Mean Cq of the positive control per run and target, with Westgard rules.":"每次运行、每个靶标阳性对照的平均 Cq，应用 Westgard 规则。",
  "Across-run rules flag unexpected control behaviour. R-4s is not applied to run means. Investigate lot, extraction batch, assay and instrument effects.":"跨运行规则提示异常；不对运行均值应用 R-4s。需检查批次、提取、方法和仪器因素。",
  "Probe signal strength (positive control)":"探针信号强度（阳性对照）",
  "Amplitude (plateau above background) of the same control each run.":"同一对照每次运行的幅度（高于背景的平台值）。",
  "Falling with a stable Cq = probe or dye degradation (storage, freeze-thaw); a step at a lot change = the lot. Compare with B-H8/B-H10 to exclude the optics.":"Cq 稳定而信号下降 = 探针或染料降解（储存、反复冻融）；更换批号时出现阶跃 = 批号问题。与 B-H8/B-H10 对照以排除光学原因。",
  "Passive reference (ROX) level":"被动参比（ROX）水平",
  "passive reference":"被动参比",
  "Median passive-reference level of named wells.":"已命名孔被动参比水平的中位数。",
  "A step = new master-mix lot or ROX concentration.":"阶跃 = 新的预混液批号或 ROX 浓度变化。",
  "PCR efficiency from the standards":"由标准品得到的 PCR 效率",
  "% efficiency":"效率 %",
  "Efficiency of the standard curve per run and target.":"每次运行、每个靶标标准曲线的效率。",
  "A slow drop = degrading standard or reagent; outside 90–110 % fails MIQE-style acceptance.":"缓慢下降 = 标准品或试剂降解；超出 90–110 % 不符合 MIQE 风格的验收标准。",
  "NTC / blank positives":"NTC / 空白阳性",
  "share of NTC wells":"NTC 孔比例",
  "Share of negative-control wells with any Cq.":"出现任何 Cq 的阴性对照孔比例。",
  "Rising = contamination of reagents or of the working area (ISFG, MIQE).":"上升 = 试剂或工作区域受到污染（ISFG、MIQE）。",
  "Internal-control shift (inhibition)":"内控偏移（抑制）",
  "cycles":"循环",
  "Mean IC Cq shift from the configured fixed reference. Missing reference means unavailable; endogenous taxon targets are not fixed-input IPCs.":"样品内控 Cq 相对运行中位数的平均偏移。",
  "Upward drift = extraction method or kit problem.":"向上漂移 = 提取方法或试剂盒问题。",
  "Low Cq confidence":"Cq 置信度低",
  "Share of wells flagged for low Cq confidence.":"标记为 Cq 置信度低的孔比例。",
  "A rise = noisy curves, often probe or baseline problems.":"上升 = 曲线噪声大，常见于探针或基线问题。",
  "Late signal / stochastic-zone results":"晚期信号 / 随机区结果",
  "share of results":"结果比例",
  "Share of sample results falling in the late-signal or low-quantity zone.":"落在晚期信号区或低定量区的样品结果比例。",
  "A rise = sensitivity drop or poorer samples.":"上升 = 灵敏度下降或样品质量变差。",
  "Replicate precision (pooled SD, Cq < 30)":"重复孔精密度（合并标准差，Cq < 30）",
  "Cq SD":"Cq 标准差",
  "Pipetting precision; replicates above Cq 30 are left out so stochastic noise does not hide skill.":"移液精密度；Cq 30 以上的重复孔不计入，以免随机噪声掩盖技能差异。",
  "One operator's points above the others → retraining; everyone rising → pipette calibration.":"某位操作人员的点高于其他人 → 再培训；所有人都上升 → 移液器校准。",
  "Dispensed-volume spread (ROX CV)":"加样体积离散度（ROX CV）",
  "Raw passive-reference level varies with the dispensed volume.":"被动参比的原始水平随加样体积变化。",
  "High CV = uneven pipetting or bubbles.":"CV 高 = 移液不均匀或有气泡。",
  "Row / column pattern":"行 / 列模式",
  "Largest mean Cq offset of a plate row or column.":"板上某一行或某一列的最大平均 Cq 偏移。",
  "One row or column off = a faulty multichannel tip or loading-order error.":"某行或某列偏移 = 多道移液器某个吸头故障或加样顺序错误。",
  "Contamination rate by operator (funnel)":"按操作人员的污染率（漏斗图）",
  "NTC positives per operator against the number of NTCs they ran.":"每位操作人员的 NTC 阳性数与其所做 NTC 总数的对比。",
  "Outside the 99.8 % line → investigate; the funnel keeps small workloads from looking unfair.":"超出 99.8 % 线 → 调查；漏斗图可避免工作量小的人员显得不公平。",
  "Repeat / inconclusive / invalid rate by operator (funnel)":"按操作人员的重复 / 不确定 / 无效率（漏斗图）",
  "Analytical robustness per person.":"每个人的分析稳健性。",
  "As B-O5.":"同 B-O5。",
  "Manual interventions":"人工干预",
  "share of settings":"设置比例",
  "Share of settings or wells changed by hand.":"人工修改的设置或孔所占比例。",
  "High or rising → ask for documented reasons (OIG report lessons); compare operators with the funnel view.":"偏高或上升 → 要求提供书面理由（OIG 报告的经验）；用漏斗图比较操作人员。",
  "Stored calls that disagree with the SOP":"与 SOP 不一致的保存判定",
  "Consistency and fairness: do calls follow the written rules?":"一致性与公平性：判定是否遵循书面规则？",
  "Disagreement concentrated in one person or case type → training or bias check.":"不一致集中在某个人或某类案例 → 培训或偏倚核查。",
  "Copied-data events":"复制数据事件",
  "events":"事件",
  "Must be zero.":"必须为零。",
  "Any event is a forensic finding.":"任何事件都是一项取证发现。",
  "1 · Load files":"1 · 加载文件","2 · SOP":"2 · SOP","3 · Results":"3 · 结果","4 · Control panel":"4 · 控制面板","5 · Graphs":"5 · 图表","6 · Quality & forensic review":"6 · 质量与取证审核","7 · Open formats":"7 · 开放格式",
  "2 · Control panel":"2 · 控制面板",
  "3 · Load":"3 · 加载",
  "4 · Graphs":"4 · 图表",
  "5 · Quality & forensic review":"5 · 质量与取证审核",
  "6 · Open formats":"6 · 开放格式",
  "Hardware, software, method and operator control charts per instrument. Click a tile for the chart and its settings.":"按仪器显示硬件、软件、方法和操作人员控制图。点击卡片查看图表及其设置。",
  "One graph at a time for a single run, drawn with the SOP limits.":"每次显示单个运行的一张图，按 SOP 限值绘制。",
  "5 · Review":"5 · 审核",
  "Control panel":"控制面板",
  "Control charts for predictive maintenance and quality control, one instrument at a time. Each tile is one chart built from numbers the instrument wrote into its own files; the dot shows its state on the latest run (green in control, amber watch, red alarm, grey not enough data). Click a tile to open the chart, how to read it and its settings.":"用于预测性维护和质量控制的控制图，每次显示一台仪器。每张卡片是一张控制图，数据来自仪器自己写入文件的数值；圆点表示最近一次运行的状态（绿色受控，琥珀色需关注，红色报警，灰色数据不足）。点击卡片可打开图表、解读说明及其设置。",
  "Instrument":"仪器",
  "All charts":"全部图表",
  "Only charts that need attention":"仅显示需关注的图表",
  "Import history (JSON)":"导入历史（JSON）",
  "Export history (JSON)":"导出历史（JSON）",
  "Export history (CSV)":"导出历史（CSV）",
  "Remember history in this browser":"在本浏览器中保存历史",
  "Single-run diagnostic graphs":"单次运行诊断图",
  "The graphs behind several tiles, for one run at a time.":"部分卡片背后的图表，每次显示一个运行。",
  "Block temperature — LightCycler":"模块温度 — LightCycler",
  "Block, cover and zones — QuantStudio":"模块、热盖与分区 — QuantStudio",
  "Amplification curves":"扩增曲线",
  "Plate heat map":"板热图",
  "Background and plateau":"背景与平台",
  "Stored vs re-derived Ct":"保存与重新推导的 Ct",
  "Run timeline":"运行时间线",
  "runs in this instrument's history":"本仪器历史中的运行数",
  "charts in control":"受控图表",
  "charts to watch (rule alarm or limit approaching)":"需关注的图表（规则报警或接近限值）",
  "charts alarming on the latest run":"最近一次运行报警的图表",
  "charts still collecting a baseline":"仍在收集基线的图表",
  "runs loaded now":"当前加载的运行",
  "runs from the imported history":"来自导入历史的运行",
  "by operator":"按操作人员",
  "No data in these files:":"这些文件中没有数据：",
  "Only QuantStudio files carry:":"仅 QuantStudio 文件包含：",
  "Only LightCycler files carry:":"仅 LightCycler 文件包含：",
  "Nothing needs attention in this group.":"本组没有需要关注的图表。",
  "No chart in this group has data in these files.":"本组图表在这些文件中都没有数据。",
  "Channel / target":"通道 / 靶标",
  "Chart type":"图表类型",
  "X axis":"横轴",
  "Data (CSV)":"数据（CSV）",
  "Close":"关闭",
  "source":"来源",
  "How to read it":"如何解读",
  "Alarms":"报警",
  "Settings for this chart (saved in the SOP profile)":"本图表的设置（保存在 SOP 配置文件中）",
  "Alarm action":"报警处理",
  "Baseline runs (Phase I)":"基线运行数（第一阶段）",
  "Lower specification":"规格下限",
  "Upper specification":"规格上限",
  "Warn when the limit is closer than (runs)":"距限值少于以下运行数时预警",
  "Run rules (Western Electric)":"判异规则（Western Electric）",
  "2 of 3 beyond 2σ":"3 点中 2 点超出 2σ",
  "4 of 5 beyond 1σ":"5 点中 4 点超出 1σ",
  "8 on one side":"连续 8 点在中心线同侧",
  "6 rising/falling":"连续 6 点上升/下降",
  "Reset this chart to defaults":"将本图表恢复默认",
  "Changes update the profile SHA-256 like any other SOP rule; save the profile on the SOP page to keep them.":"修改会像其他 SOP 规则一样更新配置文件的 SHA-256；请在 SOP 页面保存配置文件以保留修改。",
  "Flag for review in the forensic log":"在取证日志中标记待审核",
  "Error in the forensic log":"在取证日志中记为错误",
  "No alarm (chart only)":"不报警（仅显示图表）",
  "Individuals (I) with run rules":"单值图（I）及判异规则",
  "EWMA (slow drift)":"EWMA（缓慢漂移）",
  "CUSUM (small persistent shift)":"CUSUM（小幅持续偏移）",
  "Trend / wear line with prediction":"趋势 / 磨损线及预测",
  "X̄–S (within-run subgroups)":"X̄–S（运行内子组）",
  "p-chart (proportion)":"p 图（比例）",
  "u-chart (events per hour)":"u 图（每小时事件数）",
  "c-chart (count)":"c 图（计数）",
  "Funnel plot by operator":"按操作人员的漏斗图",
  "Run order":"运行顺序",
  "Date":"日期",
  "Cumulative run hours":"累计运行小时",
  "Block cycles (QuantStudio)":"模块循环数（QuantStudio）",
  "in control":"受控",
  "watch":"关注",
  "alarm":"报警",
  "no data":"无数据",
  "the fitted line reaches":"拟合线达到",
  "at":"于",
  "8 · Control charts":"8 · 控制图",
  "Open the control panel":"打开控制面板",
  "history rows read":"条历史记录已读取",
  "Block temperature trace (LightCycler temperature log)":"模块温度曲线（LightCycler 温度日志）",
  "Load .ixo or .eds runs (or import an instrument history) to fill the control panel.":"请加载 .ixo 或 .eds 运行（或导入仪器历史）以填充控制面板。",
  "Control limits need about 20 runs per instrument.":"每台仪器约需 20 次运行才能建立控制限。",
  "Import an instrument history or load more runs to make the alarms meaningful.":"请导入仪器历史或加载更多运行，使报警具有意义。",
  "in control":"受控",
  "alarm in the last 5 runs":"最近 5 次运行中有报警",
  "alarms switched off":"已关闭报警",
  "no data in these files":"这些文件中没有数据",
  "needs two or more operators":"需要两位或以上操作人员",
  "needs five or more runs":"需要五次或以上运行",
  "all operators within limits":"所有操作人员均在限值内",
  "beyond 3σ":"超出 3σ",
  "off the trend line (3σ)":"偏离趋势线（3σ）",
  "EWMA beyond limit":"EWMA 超限",
  "upward shift (CUSUM)":"向上偏移（CUSUM）",
  "downward shift (CUSUM)":"向下偏移（CUSUM）",
  "above p limit":"超出 p 图上限",
  "above u limit":"超出 u 图上限",
  "above c limit":"超出 c 图上限",
  "mean beyond limit":"均值超限",
  "spread (S) beyond limit":"离散度（S）超限",
  "below specification":"低于规格",
  "above specification":"高于规格",
  "The block moves between these two temperatures faster than usual: after a service, a cleaned fan filter or a cooler room. Harmless; if it coincides with a step in overshoot or offset, start a new baseline on the service date.":"加热块在这两个温度之间的移动比平时快：维修、清洁风扇过滤网或室温较低之后。无害；若与过冲或偏移的阶跃同时出现，在维修日期设定新基线。",
  "The block needs longer to move between these two temperatures, so every cycle spends less time at the programmed hold. A cooling transition (e.g. 95 → 60 °C) getting longer = heat removal (clean fan filters, check fans, room temperature); heating transitions getting longer = Peltier ageing. Samples spend more time at intermediate temperatures, which can favour non-specific annealing.":"加热块在这两个温度之间移动所需时间变长，每个循环在设定保持温度的时间减少。降温转换（如 95 → 60 °C）变长 = 散热问题（清洁风扇过滤网、检查风扇、室温）；升温转换变长 = Peltier 老化。样品在中间温度停留更久，可能促进非特异性退火。",
  "Heating is slower than usual. A single low run: plate not seated, wrong plate type, blocked air vents or a warm room that day. A slow fall over many runs: Peltier elements or thermal paste ageing — plan a thermal service before the specification (4.3 °C/s on the LightCycler) is reached.":"加热比平时慢。单次偏低：当天板未放好、板型错误、通风口堵塞或室温偏高。多次运行缓慢下降：Peltier 元件或导热膏老化 — 在达到规格下限（LightCycler 为 4.3 °C/s）前安排热系统维护。",
  "Cooling is slower than usual: the heat sink is not getting rid of heat. First clean the fan filters and check that all fans run and the vents are free; then check room temperature. If cooling keeps falling while heating stays normal after cleaning, the Peltier/heat-sink contact needs service.":"冷却比平时慢：散热器散热不足。先清洁风扇过滤网，检查所有风扇运转、通风口畅通；再检查室温。清洁后若冷却仍持续下降而加热正常，需维修 Peltier/散热器接触。",
  "The block overshoots less than it used to (CUSUM drifting down). The temperature controller or the sensor calibration has changed — typical after a service or recalibration. Check that the reading temperature (B-H4) did not shift at the same time.":"加热块过冲比以往小（CUSUM 向下漂移）。温度控制器或传感器校准已改变 — 常见于维修或重新校准后。检查读数时温度（B-H4）是否同时偏移。",
  "The block reaches a stable temperature faster than usual. Harmless in itself; if it coincides with a step in overshoot and offset, the controller was re-tuned or recalibrated (start a new baseline).":"加热块比平时更快达到稳定温度。本身无害；若与过冲和偏移的阶跃同时出现，说明控制器已重新调整或校准（设定新基线）。",
  "At the moment of reading the block is colder than usual compared with the setpoint (more negative offset). Real sample temperature is lower: annealing becomes less stringent. Check cooling (B-H2) and room temperature; persistent change needs a temperature verification plate or recalibration. S above its limit = temperature not stable during the reading.":"读数时加热块相对设定值比平时更冷（偏移更负）。实际样品温度更低：退火严格性降低。检查冷却（B-H2）和室温；持续变化需用温度验证板或重新校准。S 超限 = 读数期间温度不稳定。",
  "The six block zones agree better than usual. Harmless; typical after a block service or recalibration.":"六个区域温度一致性比平时更好。无害；常见于加热块维修或校准后。",
  "The heat sink stays cooler than usual: cooler room or cleaned fans/filters. Harmless.":"散热器温度比平时低：室温较低或风扇/过滤网已清洁。无害。",
  "The heated cover is colder than its setpoint: condensation can form under the seal and change reaction volumes. Check that the cover heats and that the run was not started with the cover disabled; recurring = cover heater service.":"热盖温度低于设定值：封膜下可能形成冷凝，改变反应体积。检查热盖是否加热、运行是否在关闭热盖的情况下启动；反复出现 = 维修热盖加热器。",
  "The lamp reference reading is lower than usual: less light reaches the reference sensor. Lamp near the end of its range, light guide or filter dirty, or the lamp was not warmed up. Check lamp intensity % and hours in Tools → Instruments.":"灯参考读数比平时低：到达参考传感器的光减少。灯接近寿命末期、光导或滤光片脏污，或灯未充分预热。在 Tools → Instruments 中检查灯强度 % 和使用小时数。",
  "Lamp output falls during the run more than usual: the lamp is unstable (ageing) or was not warmed up. Late-cycle fluorescence may be under-reported; check the lamp.":"运行中灯输出下降超过平常：灯不稳定（老化）或未充分预热。后期循环荧光可能偏低；检查灯。",
  "The LED is driven with less current than usual: either the LED is brighter than expected (after a service) or the driver is limiting. Check that signal levels (A-H3) did not drop.":"LED 驱动电流比平时低：LED 比预期更亮（维修后）或驱动器限流。检查信号水平（A-H3）是否下降。",
  "The LED runs cooler than usual: cooler room or improved airflow. Harmless.":"LED 结温比平时低：室温较低或气流改善。无害。",
  "Shorter exposures than usual: the signal is brighter (more template, new reagent lot, higher probe concentration) or the light source is stronger after a service. Check for saturation (B-H12).":"曝光时间比平时短：信号更亮（模板更多、新试剂批次、探针浓度更高）或维修后光源更强。检查饱和（B-H12）。",
  "Fewer saturated images than usual: normal.":"饱和图像比平时少：正常。",
  "The new uniformity calibration shows the plate edges relatively darker than before: optics or illumination changed. Check that the calibration was done with the correct plate, and watch for edge effects in the results.":"新的均一性校准显示板边缘相对以前更暗：光学或照明发生变化。检查校准是否使用了正确的板，并注意结果中的边缘效应。",
  "The background calibration offset is lower than before: cleaner block or new calibration plate. Harmless.":"背景校准偏移比以前低：加热块更干净或使用了新校准板。无害。",
  "The well spots found by the ROI calibration are smaller than before: focus or alignment changed. Wells may be read off-centre; repeat the ROI calibration.":"ROI 校准找到的孔光斑比以前小：焦距或对准发生变化。孔可能被偏心读取；重新进行 ROI 校准。",
  "Filter-wheel moves are faster than usual: typical after a motor service or firmware change. Harmless.":"滤光轮移动比平时快：常见于电机维修或固件更新后。无害。",
  "Fewer slow moves than usual: normal.":"慢速移动比平时少：正常。",
  "The filter-wheel position offset stepped down: the wheel slipped, was re-homed or serviced. Wrong filter positions change the signal in every channel; check the dye calibration if unexplained.":"滤光轮位置偏移向下阶跃：滤光轮打滑、重新归位或维修过。滤光片位置错误会改变所有通道的信号；如无法解释，检查染料校准。",
  "Camera readout is faster than usual: firmware or controller change. Harmless.":"相机读出比平时快：固件或控制器变化。无害。",
  "Switching between channels is faster than usual: firmware or mechanical change. Harmless, but note it.":"通道切换比平时快：固件或机械变化。无害，但应记录。",
  "The cover lowers faster than usual: typical after lubrication or a drive service. Harmless.":"热盖下降比平时快：常见于润滑或驱动维修后。无害。",
  "The cover rises faster than usual: harmless.":"热盖上升比平时快：无害。",
  "Background fluorescence is lower than usual: less dye or probe in the wells, a different plate or seal, less volume, or weaker excitation. Check reagent preparation and the exposure chart (B-H11).":"背景荧光比平时低：孔中染料或探针减少、板或封膜不同、体积减少或激发光减弱。检查试剂配制和曝光图（B-H11）。",
  "End-point fluorescence is lower than usual: weaker amplification (inhibition, degraded reagents, less template) or weaker optics. If the positive-control Cq is normal, suspect the probe or the optics.":"终点荧光比平时低：扩增变弱（抑制、试剂降解、模板减少）或光学变弱。若阳性对照 Cq 正常，怀疑探针或光学部件。",
  "The run finished faster than usual for this protocol: the run was stopped early or cycles were skipped. Check the run was complete before accepting results.":"该程序运行比平时快：运行被提前停止或跳过了循环。接受结果前确认运行完整。",
  "The instrument answers the PC faster than usual: harmless (firmware or PC change).":"仪器响应 PC 比平时快：无害（固件或 PC 变化）。",
  "The 1-s timer fires more punctually than usual: harmless.":"1 秒定时器比平时更准时：无害。",
  "The scheduler falls behind less often: normal.":"调度器落后的次数减少：正常。",
  "Images are processed sooner than usual: harmless.":"图像处理比平时更早开始：无害。",
  "Image analysis is faster than usual: harmless (firmware update).":"图像分析比平时快：无害（固件更新）。",
  "The run finished earlier than the software predicted: the prediction model changed, or the run was shortened. Check that the run completed.":"运行比软件预测的更早结束：预测模型改变或运行被缩短。确认运行已完成。",
  "Data were packed for the PC faster than usual: harmless.":"数据比平时更快打包给 PC：无害。",
  "Fewer command errors than usual: normal.":"命令错误比平时少：正常。",
  "Cycles are more regular than usual: harmless.":"循环比平时更规律：无害。",
  "Fewer late temperature-log intervals: normal.":"温度日志延迟间隔减少：正常。",
  "Fewer invalid readings: normal.":"无效读数减少：正常。",
  "Fewer wells whose stored Ct cannot be reproduced: normal.":"存储 Ct 无法复现的孔减少：正常。",
  "Results were finalised sooner after the run than usual: good practice.":"运行后结果定稿比平时更快：良好做法。",
  "Fewer forensic findings than usual: normal.":"法证发现比平时少：正常。",
  "The positive control amplified earlier than its range: more control template (new lot, pipetting), contamination, or a more efficient reaction. Westgard rules decide whether the run is rejected; check the control lot and pipetting.":"阳性对照扩增早于其范围：对照模板更多（新批次、移液）、污染或反应效率更高。由 Westgard 规则决定是否拒绝该运行；检查对照批次和移液。",
  "The probe signal of the control is weaker than usual: probe degradation (light, freeze–thaw), a new lot with less signal, wrong dye/quencher setup or weaker optics. Weak signal makes Cq calls less reliable; check reagent storage and lot.":"对照的探针信号比平时弱：探针降解（光照、反复冻融）、新批次信号较弱、染料/淬灭剂设置错误或光学变弱。信号弱会降低 Cq 判读可靠性；检查试剂储存和批次。",
  "The passive reference (ROX) is lower than usual: less master mix dispensed, a master mix without or with less ROX, or wrong dye settings. Normalised results may be noisier; check the master mix and pipetting.":"被动参比（ROX）比平时低：分配的预混液减少、预混液不含或含较少 ROX，或染料设置错误。归一化结果可能更嘈杂；检查预混液和移液。",
  "PCR efficiency is lower than usual (below 90 % is outside MIQE): inhibition, degraded reagents, poor primer/probe, or wrong dilutions of the standards. Quantities will be biased; repeat the standard curve.":"PCR 效率比平时低（低于 90 % 超出 MIQE）：抑制、试剂降解、引物/探针不佳或标准品稀释错误。定量将有偏差；重做标准曲线。",
  "Fewer positive negative controls than usual: normal.":"阳性阴性对照比平时少：正常。",
  "The internal control in samples amplifies earlier than the configured fixed reference Cq. Check control input, assay settings and reference applicability before attributing a cause.":"样品中的内对照扩增早于运行中位数：加入的内对照更多，或中位数受抑制样品影响。通常无害；检查内对照加量。",
  "Fewer low-confidence Cq calls: normal.":"低置信度 Cq 减少：正常。",
  "Fewer results in the late or stochastic zone: normal.":"晚期或随机区的结果减少：正常。",
  "Replicates agree better than usual: good pipetting. Harmless.":"重复孔一致性比平时好：移液良好。无害。",
  "The dispensed volume is more even than usual: good. Harmless.":"分配体积比平时更均匀：良好。无害。",
  "(A lower value is always good — no action.)":"（值越低越好 — 无需处理。）",
  "(Below the funnel is not possible for a rate — no action.)":"（比率不可能低于漏斗 — 无需处理。）",
  "Fewer manual changes than usual: normal.":"手动修改比平时少：正常。",
  "Fewer calls disagree with the SOP: normal.":"与 SOP 不一致的判读减少：正常。",
  "(Zero is the expected value.)":"（期望值为零。）",
  "Heating is faster than usual. Usually harmless: after a service, a new block or a firmware change. If isolated, check the run used the same protocol and plate; very fast ramps with a larger overshoot can stress samples.":"加热比平时快。通常无害：维修、更换加热块或固件更新之后。若为孤立点，检查该运行是否使用相同程序和板型；过快的升温伴随更大过冲可能影响样品。",
  "Cooling is faster than usual. Typical after cleaning the filters, a fan replacement or a service, or in a cooler room. Note the event and, if it was a service, start a new baseline on that date.":"冷却比平时快。常见于清洁过滤网、更换风扇或维修之后，或室温较低时。记录该事件；如为维修，在该日期设定新基线。",
  "The block overshoots more than it used to (CUSUM drifting up). The controller is compensating for a slower block, or the sensor is ageing. Samples briefly see higher temperatures; check heating rate (B-H1) and plan a temperature verification.":"加热块过冲比以往大（CUSUM 向上漂移）。控制器在补偿变慢的加热块，或传感器老化。样品会短暂承受更高温度；检查加热速率（B-H1）并安排温度验证。",
  "The block needs longer to settle. With normal ramp rates: control tuning or sensor lag. With slower ramps as well: thermal ageing. Long settling shortens the real hold time at the setpoint and can lower efficiency.":"加热块稳定所需时间变长。升降温速率正常时：控制参数或传感器滞后。升降温同时变慢时：热系统老化。稳定时间过长会缩短在设定温度的实际保持时间，可能降低扩增效率。",
  "At the moment of reading the block is warmer than usual compared with the setpoint. Real sample temperature is higher: annealing is more stringent and weakly binding probes can lose signal. Typical after a recalibration (start a new baseline); otherwise verify with a temperature plate. S above its limit = temperature not stable during the reading.":"读数时加热块相对设定值比平时更热。实际样品温度更高：退火更严格，结合较弱的探针可能信号降低。常见于重新校准后（设定新基线）；否则用温度验证板核实。S 超限 = 读数期间温度不稳定。",
  "The block zones disagree more than usual: wells in different parts of the plate see different temperatures, which shows up as edge or row/column Cq patterns (B-O3). Check plate seating and seal; if it persists or exceeds 1.5 °C, request a block uniformity service.":"各区域温差比平时大：板上不同位置的孔温度不同，表现为边缘或行/列 Cq 模式（B-O3）。检查板放置和封膜；若持续或超过 1.5 °C，申请加热块均一性维修。",
  "The heat sink runs hotter than usual: airflow is reduced (dust in filters, failing fan, instrument too close to a wall) or the room is warm. Expect slower cooling (B-H2). Clean filters, check fans and clearance.":"散热器温度比平时高：气流减少（过滤网积尘、风扇故障、仪器离墙太近）或室温偏高。冷却会变慢（B-H2）。清洁过滤网，检查风扇和间距。",
  "The heated cover is warmer than its setpoint: control fault or sensor error. Seals can deform; report to service if repeated.":"热盖温度高于设定值：控制故障或传感器误差。封膜可能变形；反复出现请联系维修。",
  "The lamp reference reading is higher than usual: typically a new lamp or a service (start a new baseline). Otherwise a reference-sensor fault; check the lamp intensity % in the instrument software.":"灯参考读数比平时高：通常是换了新灯或维修（设定新基线）。否则为参考传感器故障；在仪器软件中检查灯强度 %。",
  "Lamp output rises during the run more than usual: the lamp was still warming up at the start, or it flickers. Early-cycle baselines can be affected; allow warm-up and check the lamp.":"运行中灯输出上升超过平常：开始时灯仍在预热，或灯闪烁。早期循环基线可能受影响；确保预热并检查灯。",
  "The LED needs more current than usual to give the same light: normal LED ageing. The trend line forecasts when the driver will reach its limit — plan an optics service before that.":"LED 需要比平时更大的电流才能输出相同光强：LED 正常老化。趋势线预测驱动器何时达到极限 — 在此之前安排光学维修。",
  "The LED runs hotter than usual: reduced cooling of the optics (fans, filters, room temperature) or higher drive current (B-H10). Heat shortens LED life and can shift its colour; check airflow.":"LED 结温比平时高：光学部件冷却不足（风扇、过滤网、室温）或驱动电流升高（B-H10）。高温缩短 LED 寿命并可能改变光谱；检查气流。",
  "Longer exposures than usual: the instrument is compensating for weak light — weaker probe or dye, wrong plate or seal, dirty optics, or an ageing lamp/LED. If it keeps rising over many runs, service the optics.":"曝光时间比平时长：仪器在补偿弱光 — 探针或染料变弱、板或封膜错误、光学部件脏污或灯/LED 老化。若多次运行持续上升，维修光学部件。",
  "More well images are saturated: signal too strong for the camera (too much template or dye, wrong exposure settings, reflective plate). Saturated wells give wrong curve shapes and Cq; dilute samples or check the plate type.":"饱和的孔图像增多：信号对相机过强（模板或染料过多、曝光设置错误、反光板）。饱和孔的曲线形状和 Cq 不准确；稀释样品或检查板型。",
  "The new uniformity calibration shows the edges relatively brighter than before: optics or illumination changed, or the calibration plate differed. Confirm with a repeat calibration before accepting it.":"新的均一性校准显示边缘相对以前更亮：光学或照明发生变化，或校准板不同。接受前请重复校准确认。",
  "The background calibration offset is higher: contamination (fluorescent residue) on the block or optics, or a light leak. Clean the block, repeat the background calibration.":"背景校准偏移更高：加热块或光学部件有污染（荧光残留）或漏光。清洁加热块，重新进行背景校准。",
  "The well spots are larger than before: focus or alignment changed, or a different plate type was used for calibration. Repeat the ROI calibration with the correct plate.":"孔光斑比以前大：焦距或对准发生变化，或校准使用了不同板型。用正确的板重新进行 ROI 校准。",
  "Filter-wheel moves are slower: friction in the bearing, a weakening motor or dust. The wheel may start to miss positions (B-H15). Plan a service if the rise continues.":"滤光轮移动变慢：轴承摩擦、电机变弱或积尘。滤光轮可能开始定位偏差（B-H15）。若持续上升，安排维修。",
  "More filter-wheel moves take longer than 500 ms: mechanical wear or intermittent motor problems, often before the median (B-H14) changes. Plan a service.":"超过 500 ms 的滤光轮移动增多：机械磨损或电机间歇性问题，通常早于中位数（B-H14）的变化。安排维修。",
  "The filter-wheel position offset stepped up: the wheel slipped, was re-homed or serviced. Check the dye calibration if unexplained.":"滤光轮位置偏移向上阶跃：滤光轮打滑、重新归位或维修过。如无法解释，检查染料校准。",
  "Camera readout takes longer than usual. A jump points to the camera or its connection; a slow rise, together with the software charts (B-S1–S4), points to the embedded computer slowing down.":"相机读出时间比平时长。突然跳升指向相机或其连接；缓慢上升且伴随软件图表（B-S1–S4）变化，指向嵌入式计算机变慢。",
  "Switching between channels is slower: filter wheels, the camera readout or the instrument computer are slowing down. The manual allows < 0.65 s for the filter switch; if the rise continues, plan a service.":"通道切换变慢：滤光轮、相机读出或仪器计算机变慢。手册规定滤光片切换 < 0.65 s；若持续上升，安排维修。",
  "The cover takes longer to lower: the drive mechanism is wearing or needs lubrication, or something obstructs it (tall plate, misplaced adapter). The trend forecasts when the drive will reach its limit.":"热盖下降时间变长：驱动机构磨损或需润滑，或有阻碍（板太高、适配器放错）。趋势线预测驱动何时达到极限。",
  "The cover takes longer to rise: drive wear or the cover sticking to the seal. Check the seal type and the drive.":"热盖上升时间变长：驱动磨损或热盖粘在封膜上。检查封膜类型和驱动。",
  "Background fluorescence is higher than usual: more probe or a degraded probe (free dye), fluorescent contamination, a different plate type, or a light leak. Check the reagent lot and plate type.":"背景荧光比平时高：探针过多或探针降解（游离染料）、荧光污染、板型不同或漏光。检查试剂批次和板型。",
  "End-point fluorescence is higher than usual: more template or probe, a new reagent lot, or a brighter light source after service. Check for saturation (B-H12).":"终点荧光比平时高：模板或探针更多、新试剂批次，或维修后光源更亮。检查饱和（B-H12）。",
  "The run took longer than usual for this protocol: slower ramps (B-H1/B-H2), longer exposures (B-H11), a pause, or the instrument computer slowing. Look at those charts for the same run.":"该程序运行比平时慢：升降温变慢（B-H1/B-H2）、曝光变长（B-H11）、暂停或仪器计算机变慢。查看同一运行的相关图表。",
  "The instrument answers the PC more slowly: embedded computer busy or ageing, storage slow, or network/USB problems. Rising together with B-S2/B-S3 = instrument computer; alone = PC or connection.":"仪器响应 PC 变慢：嵌入式计算机繁忙或老化、存储慢或网络/USB 问题。与 B-S2/B-S3 同时上升 = 仪器计算机；单独上升 = PC 或连接。",
  "The 1-s timer fires late: the embedded computer is overloaded or its storage is slow. Timing of steps and readings can drift; if it keeps rising, request a vendor check of the instrument computer.":"1 秒定时器延迟触发：嵌入式计算机过载或存储慢。步骤和读数的时间可能漂移；若持续上升，请厂商检查仪器计算机。",
  "The task scheduler falls behind more often: the instrument computer cannot keep up. Watch reply time (B-S1) and processing delay (B-S3); a vendor check may be needed.":"任务调度器更频繁落后：仪器计算机跟不上。关注响应时间（B-S1）和处理延迟（B-S3）；可能需要厂商检查。",
  "Images wait longer before processing: the instrument computer is busy, storage is slow or nearly full. Clear old data on the instrument; persistent rise = vendor check.":"图像处理前等待时间变长：仪器计算机繁忙、存储慢或接近满。清理仪器上的旧数据；持续上升 = 厂商检查。",
  "Image analysis takes longer: the instrument computer is slowing (storage, memory) or the plate layout is heavier (more wells, more dyes). Compare with runs of the same plate layout.":"图像分析时间变长：仪器计算机变慢（存储、内存）或板布局更复杂（更多孔、更多染料）。与相同板布局的运行比较。",
  "The run took longer than the software predicted: slower ramps, longer exposures or computer delays add up. Look at the thermal and software charts for the same run.":"运行时间比软件预测的长：升降温变慢、曝光变长或计算机延迟累积。查看同一运行的热和软件图表。",
  "Data were packed long after the run ended: the file was saved or transferred late (PC off, network down, run left on the instrument). For forensic review, check that nothing was changed in between.":"运行结束很久后数据才打包：文件保存或传输延迟（PC 关闭、网络中断、运行留在仪器上）。法证审查时，确认期间未做任何修改。",
  "More command errors than usual: communication problems between PC and instrument, a firmware/software mismatch or a hardware fault. Read the instrument log for the run and contact service if it repeats.":"命令错误比平时多：PC 与仪器通信问题、固件/软件不匹配或硬件故障。查看该运行的仪器日志，反复出现请联系维修。",
  "Cycle length varies more within the run: the instrument paused, waited for the computer, or thermal steps took variable time. Irregular cycles can change Cq; check the run timeline graph.":"运行内循环时长波动变大：仪器暂停、等待计算机，或热步骤耗时不一。不规律的循环可能改变 Cq；查看运行时间线图。",
  "More temperature-log intervals exceed 500 ms: the control loop is being interrupted — computer overload or a communication problem. Temperature control may be affected; check the thermal charts.":"超过 500 ms 的温度日志间隔增多：控制回路被打断 — 计算机过载或通信问题。温度控制可能受影响；查看热相关图表。",
  "More fluorescence readings are marked invalid by the instrument: optics, lamp or camera problems, or the signal was out of range. Check exposure (B-H11) and lamp (B-H8); affected wells may need repeating.":"被仪器标记为无效的荧光读数增多：光学、灯或相机问题，或信号超出范围。检查曝光（B-H11）和灯（B-H8）；受影响的孔可能需要重做。",
  "More wells have a stored Ct that the page cannot reproduce from the stored data: manual threshold or baseline changes, a software version change, or data edited after analysis. Check the analysis settings and the audit trail.":"存储 Ct 无法由存储数据复现的孔增多：手动修改了阈值或基线、软件版本变化，或分析后数据被编辑。检查分析设置和审计追踪。",
  "The file was last changed much later than usual after the run: late analysis, or re-analysis long after the run. For forensic review, check who changed what and why (audit trail).":"文件最后修改时间比平时晚得多：分析延迟，或运行后很久重新分析。法证审查时，检查谁修改了什么以及原因（审计追踪）。",
  "More forensic findings than usual for one run: open the Quality & forensic review tab for this run and resolve each finding before accepting the results.":"单次运行的法证发现比平时多：打开该运行的质量与法证审查页，在接受结果前逐项处理。",
  "The positive control amplified later than its range: degraded control or reagents, inhibition, pipetting error, or weaker optics. A trend over several runs points to reagent storage or lot ageing; a single point to the run itself.":"阳性对照扩增晚于其范围：对照或试剂降解、抑制、移液错误或光学变弱。多次运行的趋势指向试剂储存或批次老化；单个点指向该运行本身。",
  "The probe signal is stronger than usual: a new lot, higher probe concentration or a stronger light source. Check for saturation (B-H12) and that thresholds still suit the curves.":"探针信号比平时强：新批次、探针浓度更高或光源更强。检查饱和（B-H12）以及阈值是否仍适合曲线。",
  "The passive reference is higher than usual: more volume, a master mix with more ROX, or evaporation concentrating the wells. Check the master mix type and the seal.":"被动参比比平时高：体积更大、预混液 ROX 更多，或蒸发使孔内浓缩。检查预混液类型和封膜。",
  "PCR efficiency is higher than usual (above 110 % is outside MIQE): usually a pipetting or dilution error in the standards, inhibition in the concentrated standards, or primer-dimers. Repeat the dilution series.":"PCR 效率比平时高（高于 110 % 超出 MIQE）：通常是标准品移液或稀释错误、高浓度标准品中的抑制或引物二聚体。重做稀释系列。",
  "More no-template controls show a Cq: contamination (reagents, pipettes, bench, amplicon carry-over) or probe degradation giving false signal. Stop, decontaminate, replace reagents; results of affected runs need review.":"出现 Cq 的无模板对照增多：污染（试剂、移液器、台面、扩增产物残留）或探针降解产生假信号。停止工作、去污、更换试剂；受影响运行的结果需审查。",
  "The internal control in samples is delayed: inhibition from the sample matrix or extraction carry-over (ethanol, salts), or extraction losses. Affected samples may give false negatives; re-extract or dilute.":"样品中的内对照延迟：样品基质抑制或提取残留（乙醇、盐），或提取损失。受影响样品可能出现假阴性；重新提取或稀释。",
  "More wells have low Cq confidence: noisy or odd-shaped curves from weak probes, bubbles, evaporation or low template. Review the flagged curves before reporting.":"低 Cq 置信度的孔增多：弱探针、气泡、蒸发或模板少导致的噪声或异常曲线。报告前审查被标记的曲线。",
  "More results fall in the late-signal or stochastic zone: low template amounts, inhibition, degraded samples or less sensitive reagents. These results are less reliable; follow the SOP for repeats.":"落在晚期信号或随机区的结果增多：模板量低、抑制、样品降解或试剂灵敏度降低。这些结果可靠性较低；按 SOP 重复。",
  "Replicates agree less than usual: pipetting imprecision (technique, uncalibrated pipette, bubbles), poor mixing or bad plate sealing. Check the pipette calibration and retrain if it is linked to one operator.":"重复孔一致性比平时差：移液不精确（技术、移液器未校准、气泡）、混合不充分或封板不良。检查移液器校准；若与某一操作人员相关，需再培训。",
  "Dispensed volumes vary more across the plate: pipetting technique, a pipette out of calibration or a failing multichannel channel. Check the pipettes and the operator's technique.":"板上分配体积差异变大：移液技术、移液器超出校准或多道移液器某通道故障。检查移液器和操作人员技术。",
  "One plate row or column differs from the rest: a blocked or faulty multichannel tip, a pipetting order error, or a block zone problem (B-H5). Look at the plate heat map to see which row or column.":"某一行或列与其他不同：多道移液器吸头堵塞或故障、移液顺序错误，或加热块区域问题（B-H5）。查看板热图以确定是哪一行或列。",
  "This operator's NTC positive rate is higher than expected for their workload: outside 95 % = watch, outside 99.8 % = investigate the operator's contamination-control technique (gloves, tips, workflow) and offer retraining.":"该操作人员的 NTC 阳性率高于其工作量下的预期：超出 95 % = 关注，超出 99.8 % = 调查其防污染技术（手套、吸头、流程）并提供再培训。",
  "This operator gets more repeats, inconclusive or invalid results than expected for their workload: check sample handling, pipetting and SOP understanding; use it for training, not ranking.":"该操作人员的重复、不确定或无效结果多于其工作量下的预期：检查样品处理、移液和对 SOP 的理解；用于培训而非排名。",
  "More settings or wells were changed by hand (threshold, baseline, omitted wells, manual calls): the automatic analysis does not suit the data, or results were adjusted. Each change should be justified in the record.":"手动修改的设置或孔增多（阈值、基线、剔除孔、手动判读）：自动分析不适合数据，或结果被调整。每项修改都应在记录中说明理由。",
  "More stored calls disagree with the SOP rules: calls were made by hand, the software settings differ from the SOP, or the SOP profile loaded in the page is not the one in use. Review each disagreement.":"与 SOP 规则不一致的存储判读增多：判读为手动、软件设置与 SOP 不同，或页面加载的 SOP 配置不是实际使用的。逐项审查不一致之处。",
  "Identical curves or Cq values were found where independent data are expected: copied or duplicated data. This is a forensic finding — secure the original files and investigate.":"在应为独立数据处发现相同的曲线或 Cq 值：数据被复制或重复。这是法证发现 — 保全原始文件并调查。",
  "What a result outside the limits means":"超出限值的结果意味着什么",
  "▼ Below the lower limit":"▼ 低于下限",
  "▲ Above the upper limit":"▲ 高于上限",
  "Meaning":"含义",
  "▼ below":"▼ 偏低",
  "▲ above":"▲ 偏高",
  "Direction":"方向",
  "Below the limit":"低于限值",
  "Above the limit":"高于限值",
  "1 · Load files":"1 · 加载文件","2 · SOP":"2 · SOP","3 · Results":"3 · 结果","4 · Control panel":"4 · 控制面板","5 · Graphs":"5 · 图表","6 · Quality & forensic review":"6 · 质量与取证审核","7 · Open formats":"7 · 开放格式",
  "2 · Control panel":"2 · 控制面板",
  "3 · Load":"3 · 加载",
  "4 · Graphs":"4 · 图表",
  "5 · Quality & forensic review":"5 · 质量与取证审核",
  "6 · Open formats":"6 · 开放格式",
  "Drop the files. Integrity is checked on reading.":"拖入文件，读取时即校验完整性。",
  "Pick or open your laboratory profile; outcomes and run acceptance follow it.":"选择或打开实验室配置文件，结果判定与运行验收均据此进行。",
  "One graph at a time, drawn with the SOP limits; download SVG, PNG or the data.":"每次显示一张图，按 SOP 限值绘制；可下载 SVG、PNG 或数据。",
  "4 · Review":"4 · 审核",
  "Forensic log, plate, controls, curves and instrument records.":"取证日志、板图、对照、曲线与仪器记录。",
  "One row per file. Open the Review tab for the forensic log.":"每个文件一行。取证日志请见“审核”标签页。",
  "Cycles":"循环数",
  "Cq results":"Cq 结果",
  "Tm results":"Tm 结果",
  "Active channels":"有效通道",
  "Settings read from one experiment file (details)":"从单个实验文件读取的设置（详情）",
  "Download for all runs (CSV)":"下载全部运行（CSV）",
  "Laboratory SOP profile":"实验室 SOP 配置文件",
  "State your laboratory's own acceptance and interpretation rules once, save them as a profile file and reuse it. The stored Cq values and calls are never changed; every outcome says which rule produced it, and every export carries the profile's name, version and SHA-256.":"将本实验室的验收与结果解释规则一次性写好，保存为配置文件并重复使用。保存的 Cq 值与判定不会被修改；每个结果都注明产生它的规则，每个导出文件都带有配置文件的名称、版本与 SHA-256。",
  "Start from":"起始模板",
  "Generic qPCR (MIQE-style defaults)":"通用 qPCR（MIQE 风格默认值）",
  "GMO screening — qualitative (example)":"转基因筛查 — 定性（示例）",
  "Forensic DNA quantification triage (example)":"法医 DNA 定量分流（示例）",
  "Use this starting point":"使用此模板",
  "Open profile (JSON)":"打开配置文件（JSON）",
  "Save profile (JSON)":"保存配置文件（JSON）",
  "Lock profile":"锁定配置文件",
  "Results under this SOP":"按此 SOP 得出的结果",
  "Run acceptance and the interpretation of every sample, recomputed as soon as the profile changes.":"运行验收与每个样品的结果解释，配置文件一经修改即重新计算。",
  "View":"视图",
  "Sample report":"样品报告",
  "Results by target":"按靶标的结果",
  "Run acceptance criteria":"运行验收标准",
  "Runs":"运行",
  "Show":"显示",
  "Everything":"全部",
  "Only what needs action":"仅需处理的项目",
  "Positive":"阳性",
  "Negative":"阴性",
  "Inconclusive":"不确定",
  "Repeat":"重复检测",
  "Invalid":"无效",
  "Invalid run":"运行无效",
  "Control fail":"对照失败",
  "Search":"搜索",
  "Download this view (CSV)":"下载当前视图（CSV）",
  "Download SOP report (XLSX)":"下载 SOP 报告（XLSX）",
  "Download SOP bundle (ZIP)":"下载含校验值的 SOP 数据包（ZIP）",
  "Downloads follow the pseudonymisation switch in Open formats.":"下载内容遵循“开放格式”中的假名化开关。",
  "Graphs":"图表",
  "Choose one graph. Limits, colours and outcomes come from the active SOP profile, so the graphs change when the profile does. Each graph can be saved as SVG or PNG together with the numbers behind it.":"选择一张图。限值、颜色与结果均来自当前 SOP 配置文件，配置文件修改后图表随之改变。每张图均可连同其数据一起保存为 SVG 或 PNG。",
  "Graph":"图表",
  "Colour shows":"颜色表示",
  "SOP outcome":"SOP 结果",
  "Analysis status (incl. signal outside analyses)":"分析状态（含分析之外的信号）",
  "End-point fluorescence":"终点荧光",
  "Background fluorescence":"背景荧光",
  "Amplitude above background":"高于背景的幅度",
  "ΔRn with threshold (QuantStudio)":"ΔRn 与阈值（QuantStudio）",
  "Log axis":"对数坐标",
  "Role":"角色",
  "SOP control":"SOP 对照",
  "Save as SVG":"保存为 SVG",
  "Save as PNG":"保存为 PNG",
  "Download the data (CSV)":"下载数据（CSV）",
  "All graphs for this run + all runs (ZIP)":"本运行及全部运行的所有图表（ZIP）",
  "Errors and review items":"错误与待审核项",
  "Errors only":"仅错误",
  "Everything, including information":"全部（含提示信息）",
  "sample, target, reason…":"样品、靶标、原因…",
  "Profile":"配置文件",
  "SHA-256":"SHA-256",
  "State":"状态",
  "editable":"可编辑",
  "locked — fields are read-only":"已锁定 — 字段只读",
  "1 · Identity of the procedure":"1 · 程序标识",
  "Profile name":"配置文件名称",
  "Version":"版本",
  "Author / approver":"编写 / 批准人",
  "Assay":"检测项目",
  "Effective from":"生效日期",
  "Notes":"备注",
  "Starting values only. Replace every number with the value validated in your SOP.":"仅为起始值。请将每个数值替换为 SOP 中经验证的数值。",
  "2 · Targets, Cq cut-offs and late-signal zone":"2 · 靶标、Cq 截断值与晚期信号区",
  "Rows are tried top to bottom; the first whose pattern matches the target name applies. Patterns:":"按自上而下的顺序匹配，第一个与靶标名称匹配的行生效。模式：",
  ", wildcards":"，通配符",
  "for anything, or a regular expression written as":"表示任意，或写成正则表达式",
  ". A Cq above the cut-off counts as not detected. A mean Cq above the late-signal limit, or a quantity below the minimum, gets the late-signal outcome.":"。Cq 高于截断值视为未检出。平均 Cq 高于晚期信号限值，或定量值低于最小值时，给出晚期/低值结果。",
  "Target pattern":"靶标模式",
  "Kind":"类型",
  "Cq cut-off":"Cq 截断值",
  "Late-signal limit":"晚期信号限值",
  "Minimum quantity":"最小定量值",
  "Late / low outcome":"晚期 / 低值结果",
  "Add target rule":"添加靶标规则",
  "Add a row for every target in the loaded runs":"为已加载运行中的每个靶标添加一行",
  "3 · Controls: which wells, what they must show, how many per run":"3 · 对照：哪些孔、应得结果、每次运行的数量",
  "Match by the sample name (patterns as above) or by the resolved role (NTC, Blank, Negative control, Positive control, Calibrator, Standard). Leave the Cq range empty when any detection is acceptable.":"按样品名称（模式同上）或识别出的角色（NTC、Blank、Negative control、Positive control、Calibrator、Standard）匹配。任何检出均可接受时，Cq 范围留空。",
  "Control":"对照",
  "Match by":"匹配依据",
  "Pattern":"模式",
  "Targets":"靶标",
  "Expectation":"预期",
  "Cq from":"Cq 下限",
  "Cq to":"Cq 上限",
  "Min wells / run":"每次运行最少孔数",
  "If it fails":"不合格时",
  "Add control":"添加对照",
  "4 · Replicates and internal control":"4 · 重复孔与内控",
  "Minimum replicates per sample":"每个样品最少重复孔数",
  "Detected replicates needed for a positive":"判为阳性所需的检出重复孔数",
  "capped at the number of replicates present":"不超过实际重复孔数",
  "Outcome when only some replicates are detected":"仅部分重复孔检出时的结果",
  "Maximum replicate SD (Cq)":"重复孔最大标准差（Cq）",
  "Outcome when the SD is exceeded":"标准差超限时的结果",
  "Flag only (keep outcome)":"仅标记（保留结果）",
  "Maximum IC shift from the run median (cycles)":"内控相对运行中位数的最大偏移（循环）",
  "Outcome for a negative with a shifted IC":"内控偏移时阴性样品的结果",
  "Outcome when the IC / reference is not detected":"内控 / 参照基因未检出时的结果",
  "5 · Run acceptance":"5 · 运行验收",
  "Container checksum fails":"容器校验失败",
  "Reject the run":"拒收该运行",
  "Flag for review":"标记待审核",
  "Do not check":"不检查",
  "Run not completed":"运行未完成",
  "Required control missing":"缺少必需对照",
  "Standard curve outside limits":"标准曲线超出限值",
  "Minimum R²":"最小 R²",
  "Efficiency from (%)":"效率下限（%）",
  "Efficiency to (%)":"效率上限（%）",
  "Minimum dynamic range (log10)":"最小动态范围（log10）",
  "Minimum NTC-to-sample gap (cycles)":"NTC 与样品的最小间隔（循环）",
  "NTC gap too small":"NTC 间隔过小",
  "Maximum hours from run end to last change":"运行结束至最后修改的最长小时数",
  "Changed later / created after run":"事后修改 / 运行后创建",
  "Calibration expired (QuantStudio)":"校准过期（QuantStudio）",
  "Maximum block zone spread °C (QuantStudio)":"模块分区最大温差 °C（QuantStudio）",
  "Zone spread exceeded":"分区温差超限",
  "A rejected run turns every sample result into “Invalid run”":"运行被拒收时，所有样品结果改为“运行无效”",
  "6 · Outcomes, colours and report wording":"6 · 结果、颜色与报告措辞",
  "Placeholders: {sample} {target} {cq} {sd} {det} {n} {cutoff} {reason} {outcome} {run}. The colours are used by every SOP graph.":"占位符：{sample} {target} {cq} {sd} {det} {n} {cutoff} {reason} {outcome} {run}。所有 SOP 图表都使用这些颜色。",
  "Outcome":"结果",
  "Label in reports":"报告中的标签",
  "Colour":"颜色",
  "Report sentence":"报告语句",
  "7 · Graph settings":"7 · 图表设置",
  "Draw the Cq cut-off lines":"绘制 Cq 截断线",
  "Draw the late-signal lines":"绘制晚期信号线",
  "Draw the SD limit":"绘制标准差限值",
  "Edit the profile as JSON":"以 JSON 编辑配置文件",
  "Apply JSON":"应用 JSON",
  "runs accepted":"次运行通过",
  "runs accepted with review":"次运行通过（需审核）",
  "runs rejected":"次运行被拒收",
  "results needing action":"条结果需处理",
  "All runs":"全部运行",
  "Interpretation":"结果解释",
  "Report text":"报告文本",
  "Reference gene":"参照基因",
  "Internal / inhibition control":"内控 / 抑制对照",
  "Sample name":"样品名称",
  "Must be negative":"必须为阴性",
  "Must be positive":"必须为阳性",
  "Standard (no pass/fail)":"标准品（不判定）",
  "Automatic":"自动",
  "Target":"靶标",
  "Resolved role":"识别出的角色",
  "Run history":"运行历史",
  "Fluorescence":"荧光",
  "Plate":"板",
  "Results":"结果",
  "Across runs":"跨运行",
  "Run timeline — created, run, analysis, last change":"运行时间线 — 创建、运行、分析、最后修改",
  "Block, cover and zone temperature (QuantStudio log)":"模块、热盖与分区温度（QuantStudio 日志）",
  "Stored Ct against the Ct re-derived on this page":"保存的 Ct 与本页重新推导的 Ct 对比",
  "Amplification curves coloured by SOP outcome":"按 SOP 结果着色的扩增曲线",
  "Fluorescence level against Cq":"荧光水平与 Cq",
  "Background and plateau fluorescence per channel":"各通道的背景与平台期荧光",
  "Plate heat map":"板热图",
  "Signal in wells that are not in any analysis":"未纳入任何分析的孔中的信号",
  "Cq by target with SOP cut-offs":"按靶标的 Cq 与 SOP 截断值",
  "Replicate spread — mean Cq against SD":"重复孔离散度 — 平均 Cq 与标准差",
  "Standard curve with residuals and SOP limits":"含残差与 SOP 限值的标准曲线",
  "Internal control / reference Cq per sample (inhibition)":"各样品内控 / 参照基因 Cq（抑制）",
  "SOP outcomes per target":"按靶标的 SOP 结果",
  "Runs on a calendar — run time and last change":"日历上的运行 — 运行时间与最后修改",
  "Hours from run end to the last recorded change":"运行结束至最后记录修改的小时数",
  "Run acceptance grid":"运行验收网格",
  "SOP outcomes per run":"各运行的 SOP 结果",
  "Control Cq across runs with SOP range":"跨运行对照 Cq 与 SOP 范围",
  "Background and plateau fluorescence across runs":"跨运行的背景与平台期荧光",
  "Run duration and instrument use":"运行时长与仪器使用",
  "Forensic findings by area (Pareto)":"按领域的取证发现（帕累托图）",
  "All targets":"全部靶标",
  "Drawn with SOP profile":"绘制所用 SOP 配置文件",
  "Data behind this graph":"本图数据",
  "(all loaded runs)":"（全部已加载运行）",
  "Profile checksum verified":"配置文件校验值已验证",
  "Profile checksum does not match — the file was edited after it was saved":"配置文件校验值不一致 — 文件在保存后被编辑过",
  "Detected":"检出",
  "Not detected":"未检出",
  "Repeat analysis":"重复检测",
  "Invalid result":"结果无效",
  "Control accepted":"对照合格",
  "Control failed":"对照不合格",
  "Standard":"标准品",
  "Not interpreted":"未解释",
  "Accepted":"通过",
  "Accepted with review":"通过（需审核）",
  "Rejected":"拒收",
  "Template":"模板",
  "Experiment":"实验",
  "Sample":"样品",
  "Rule":"规则",
  "Wells":"孔位",
  "Detected ":"检出",
  "Mean Cq":"平均 Cq",
  "SD":"标准差",
  "Reason":"原因",
  "Stored call":"保存的判定",
  "Criterion":"标准",
  "Result":"结果",
  "SOP action":"SOP 处理",
  "Evidence":"证据",
  "Status":"状态",
  "Rejected by":"拒收原因",
  "Review":"审核",
  "Run started":"运行开始",
  "Last change":"最后修改",
  "Hours to last change":"至最后修改的小时数",
  "Level":"级别",
  "Every dated event the file carries: experiment creation, run start and end, analysis creation and edits, the last recorded change (for .eds, the newest ZIP entry date is the last save), instrument log and calibrations. Events more than 7 days from the run are listed in the table and marked at the edge.":"文件中所有带日期的事件：实验创建、运行开始与结束、分析创建与编辑、最后记录的修改（.eds 文件中最新的 ZIP 条目日期即最后保存时间）、仪器日志与校准。距运行超过 7 天的事件列在表中并标在图边缘。",
  "Stored curves of the selected target. Colour = outcome under the active SOP; dashed vertical lines = SOP Cq cut-off and late-signal limit; horizontal line = stored threshold (QuantStudio ΔRn).":"所选靶标的保存曲线。颜色 = 当前 SOP 下的结果；竖虚线 = SOP Cq 截断值与晚期信号限值；横线 = 保存的阈值（QuantStudio ΔRn）。",
  "Every physical position. Choose what the colour shows: SOP outcome, stored Cq, end fluorescence, background, amplitude, or analysis status (which also shows wells with signal that are in no analysis, and omitted wells).":"全部物理孔位。可选择颜色表示：SOP 结果、保存的 Cq、终点荧光、背景、幅度或分析状态（同时显示有信号但未纳入分析的孔及被忽略的孔）。",
  "Rising fluorescence in positions that carry no result (unnamed wells, wells left out of every analysis, or wells without a target). These are the places where a sample may have been run but not reported.":"没有结果的孔位中出现的上升荧光（未命名孔、未纳入任何分析的孔或无靶标的孔）。这些位置可能进行了检测但未报告。",
  "One point per well. Colour by SOP outcome or by role. Red dashed line: Cq cut-off; orange: late-signal limit (per target).":"每孔一个点。按 SOP 结果或角色着色。红色虚线：Cq 截断值；橙色：晚期信号限值（按靶标）。",
  "One point per sample and target with two or more detected replicates. The dashed line is the SOP maximum SD.":"每个含两个及以上检出重复孔的样品/靶标一个点。虚线为 SOP 最大标准差。",
  "Cq against log10 of the stored standard quantity, fitted by least squares on this page. The label shows slope, R², efficiency and range against the SOP limits; residuals are in the table.":"Cq 对保存的标准品定量值 log10 作图，并在本页用最小二乘法拟合。标签显示斜率、R²、效率与范围及其与 SOP 限值的比较；残差见表格。",
  "Cq of the targets the SOP marks as internal control or reference. The band is the run median ± the SOP maximum IC shift; points above it suggest inhibition or low input.":"SOP 标记为内控或参照基因的靶标 Cq。参考线为运行中位数及 SOP 允许的最大内控偏移；高于该线的点提示抑制或模板量低。",
  "End-point fluorescence (or amplitude above background) against the stored Cq. Late, low-plateau curves separate from true amplification; undetected wells are drawn at the right edge.":"终点荧光（或高于背景的幅度）与保存的 Cq 对比。晚期、低平台曲线与真实扩增可区分；未检出的孔绘于右侧边缘。",
  "For each detection channel / target: background (mean of cycles 3–10) and end-point fluorescence of every well, including wells outside the analyses. A shifted background points to plate, seal or optical problems.":"每个检测通道 / 靶标：各孔的背景（第 3–10 循环平均值）与终点荧光，包括分析之外的孔。背景偏移提示板、封膜或光学问题。",
  "Number of sample/target results per outcome under the active SOP, controls included.":"当前 SOP 下每种结果的样品/靶标结果数（含对照）。",
  "From the instrument log inside the .eds file: sample block mean, heated cover and the spread between block zones, against minutes from the first record. The dashed line is the SOP maximum zone spread.":"来自 .eds 文件中的仪器日志：样品模块平均温度、热盖温度与模块分区温差，横轴为距第一条记录的分钟数。虚线为 SOP 允许的最大分区温差。",
  "QuantStudio only: difference between the stored Ct and the crossing of the stored ΔRn with the stored threshold. Differences beyond ±0.2 require an algorithm/settings/provenance review; they do not prove that stored data were edited.":"仅限 QuantStudio：保存的 Ct 与保存的 ΔRn 和保存阈值交点之间的差值。差值超过 ±0.2 表明 Ct 写入后阈值、基线或曲线被修改过。",
  "Each run as a green dot at its start, with the experiment creation (blue, above) and the last recorded change (red, below, joined by a dashed line). Long gaps between run and last change are the first thing an auditor asks about.":"每次运行以其开始时刻的绿点表示，实验创建（蓝色，上方）与最后记录的修改（红色，下方，以虚线相连）一并标出。运行与最后修改之间的长时间间隔是审核人员首先关注的问题。",
  "Processing time per run. The dashed line is the SOP maximum; bars above it are flagged in the run acceptance.":"各运行的处理时间。虚线为 SOP 上限；超过上限的柱在运行验收中被标记。",
  "Runs (rows) against the SOP criteria (columns): green met, amber review, red rejected, grey not applicable.":"运行（行）对照 SOP 标准（列）：绿色符合，琥珀色待审核，红色拒收，灰色不适用。",
  "Stacked counts of sample/target outcomes for every loaded run.":"每个已加载运行的样品/靶标结果堆叠计数。",
  "Mean Cq of the chosen SOP control per run (Levey-Jennings style). Solid band: the Cq range written in the SOP; dotted lines: mean ± 2 SD and ± 3 SD of the loaded runs.":"所选 SOP 对照在各运行中的平均 Cq（Levey-Jennings 形式）。实色带：SOP 规定的 Cq 范围；点线：已加载运行的均值 ± 2 SD 与 ± 3 SD。",
  "Median background and median end-point fluorescence of every channel per run: slow drift here is an instrument or reagent trend.":"各运行每个通道的背景中位数与终点荧光中位数：缓慢漂移反映仪器或试剂趋势。",
  "Minutes from run start to run end, coloured by instrument. A run much shorter than its siblings with the same protocol deserves a look at the log.":"从运行开始到结束的分钟数，按仪器着色。若某运行明显短于同一程序的其他运行，应查看日志。",
  "Count of error and review findings in the forensic log, grouped by area, largest first.":"取证日志中错误与待审核发现的数量，按领域分组，从多到少排列。",
  "LightCycler 480 — raw values, open formats and quality control":"LightCycler 480 - 原始数据、开放格式与质量控制",
  "Reads a finished":"读取已完成的",
  "experiment, hands you the numbers the instrument stored, and writes them in formats that open-source tools read directly. Nothing is uploaded; everything runs in this page.":"实验，呈现仪器保存的数值，并导出为开源工具可直接读取的格式。数据不会上传，所有处理均在本页面中完成。",
  "Reads a finished .ixo experiment, hands you the numbers the instrument stored, and writes them in formats that open-source tools read directly. Nothing is uploaded; everything runs in this page.":"读取已完成的 .ixo 实验，呈现仪器保存的数值，并导出为开源工具可直接读取的格式。数据不会上传，所有处理均在本页面中完成。",
  "Language":"语言","English":"English","1 · Load files":"1 · 加载文件","2 · SOP":"2 · SOP","3 · Results":"3 · 结果","4 · Control panel":"4 · 控制面板",
  "5 · Graphs":"5 · 图表","6 · Quality review":"6 · 质量审核","6 · Quality & forensic review":"6 · 质量与取证审核","7 · Open formats":"7 · 开放格式",
  "Load an experiment":"加载实验",
  "Drop one or more":"拖入一个或多个","files, or a":"文件，也可拖入包含这些文件的",
  "containing them. Several runs can be loaded at once — the Quality review tab compares them.":"。可同时加载多个运行，并在“质量审核”中进行比较。",
  "Drop one or more .ixo files, or a .zip containing them. Several runs can be loaded at once — the Quality review tab compares them.":"拖入一个或多个 .ixo 文件，也可拖入包含这些文件的 .zip。可同时加载多个运行，并在“质量审核”中进行比较。",
  "Drop .ixo or .zip here":"将 .ixo 或 .zip 拖到这里","or click to choose files":"或点击选择文件",
  "Read the files":"读取文件","Or paste Cq values from any instrument":"或粘贴任意仪器的 Cq 值",
  "A pasted table can be tidied and downloaded again, but it carries no fluorescence, so the curve-based exports need an .ixo or .eds file. Paste or upload a table with a sample column and a Cq column — the header names are matched loosely, so exports from most instruments work as they are. A well column is used if present.":"粘贴的表格可整理后重新下载，但其中不含荧光数据，因此曲线类导出仍需要 .ixo 文件。请粘贴或上传包含样品列和 Cq 列的表格；系统会宽松匹配列名，如有孔位列也会一并使用。",
  "Upload a CSV instead":"改为上传 CSV","Read pasted values":"读取粘贴值",
  "Load the ENGL worked example":"加载 ENGL 示例",
  "Read from the experiment file":"从实验文件读取",
  "Everything below was taken out of the container itself. Nothing here was typed, assumed or defaulted — each line names the property it came from, so a value you disagree with can be traced back to the bytes it was read from.":"以下内容均直接来自实验容器，没有手工录入、推测或默认值。每一行都标明来源属性，便于追溯核对。",
  "Download this table (CSV)":"下载此表（CSV）","What was read":"读取内容",
  "Stored values, exactly as the instrument wrote them":"仪器保存的原始数值",
  "Nothing here is recomputed. Cq is the crossing point the LightCycler stored; concentration is its":"此处不重新计算任何数值。Cq 为 LightCycler 保存的交叉点，浓度来自",
  "; the call is its own classification. Download the table for your own analysis.":"；判定结果为仪器自身分类。可下载表格进行进一步分析。",
  "Nothing here is recomputed. Cq is the crossing point the LightCycler stored; concentration is its CalcConc; the call is its own classification. Download the table for your own analysis.":"此处不重新计算任何数值。Cq 为 LightCycler 保存的交叉点，浓度来自 CalcConc，判定结果为仪器自身分类。可下载表格进行进一步分析。",
  "Download Cq table (CSV)":"下载 Cq 表（CSV）","Download melting peaks (CSV)":"下载熔解峰（CSV）",
  "Formats other tools read":"其他工具可读取的格式",
  "Each download states which tool consumes it and what was checked. Where a format has a version that matters, the version that actually works is used rather than the newest or the oldest.":"每项下载均说明适用工具及已完成的检查。若格式版本会影响兼容性，则采用实际验证可用的版本。",
  "Machine-readable metadata (JSON-LD)":"机器可读元数据（JSON-LD）",
  "Dataset metadata (JSON-LD)":"数据集元数据（JSON-LD）",
  "Ready-to-run scripts":"可直接运行的脚本",
  "These assume the downloaded files are in the working directory. They are plain text — read them before running them.":"脚本假定下载文件位于工作目录中。脚本为纯文本，请在运行前检查。",
  "Preview the R script for qpcR":"预览 qpcR 的 R 脚本",
  "Preview the Python script for rdmlpython / LinRegPCR":"预览 rdmlpython / LinRegPCR 的 Python 脚本",
  "Quality review":"质量审核",
  "Inspect the plate, compare samples, review descriptive statistics, follow controls across experiments, inspect the stored curves, and audit the instrument record. Calculations are descriptive; stored Cq, calls and fluorescence are never replaced.":"查看板图、比较样品、审核描述性统计、跨实验跟踪对照、检查已保存的扩增曲线，并审计仪器记录。所有计算仅用于描述，不会替换仪器保存的 Cq、判定结果或荧光数据。",
  "Overview":"概览","Plate map":"板图","Sample comparison":"样品比较","Statistics":"统计",
  "Control charts":"质控图","Runs and QC":"运行与质控","Amplification curves":"扩增曲线",
  "Instrument records":"仪器记录","Review overview":"审核概览",
  "A compact count of recoveries and review findings. Open the detailed sheets to see every row.":"集中显示数据恢复情况与审核发现；打开各详细页面可查看全部记录。",
  "Every physical position from the block declared by the instrument, including named positions that were not included in an analysis.":"显示仪器声明温控模块中的每个物理孔位，包括已命名但未纳入分析的孔位。",
  "Experiment":"实验","Analysis / target":"分析 / 目标","Colour by":"着色依据",
  "Resolved role":"解析角色","Subset membership":"子集归属","Instrument sample type":"仪器样品类型",
  "Stored call":"保存的判定结果","Stored Cq":"保存的 Cq",
  "Download plate map (CSV)":"下载板图（CSV）","Save plate map as PNG":"将板图保存为 PNG",
  "Table-first, side-by-side comparison across every analysis. The review threshold only highlights a difference; it does not replace an assay-specific acceptance rule.":"以表格并排比较所有分析。审核阈值仅用于突出差异，不能替代检测项目自身的接收规则。",
  "Sample 1":"样品 1","Sample 2":"样品 2","Highlight when |difference| is at least":"当 |差值| 至少为以下数值时突出显示",
  "Download comparison (CSV)":"下载比较表（CSV）",
  "Statistics and mistake finding":"统计与错误排查",
  "Per-analysis descriptive statistics plus targeted review counts for missing curves, uncertain calls, large replicate spread and amplified positions omitted from every analysis.":"按分析显示描述性统计，并汇总缺失曲线、不确定判定、重复孔差异过大及未纳入分析的扩增孔位。",
  "Replicate spread review limit (Cq)":"重复孔差异审核限值（Cq）",
  "Download statistics (CSV)":"下载统计表（CSV）",
  "Levey-Jennings Cq by experiment. Replicate wells are collapsed to one point per run. Limits and Westgard rules are shown only from three or more runs.":"按实验绘制 Levey-Jennings Cq 图。每次运行的重复孔合并为一个点；至少有 3 次运行时才显示控制限和 Westgard 规则。",
  "Control identity":"对照标识","Name grouping":"名称分组",
  "Automatic root names (recommended)":"自动根名称（推荐）","Keep exact sample names":"保留完整样品名称",
  "Download chart data (CSV)":"下载图表数据（CSV）","Save chart as PNG":"将图表保存为 PNG",
  "Adjust detected control categories":"调整已识别的对照类别",
  "The automatic category applies to every dated or capitalised spelling under the same root. Change any row without renaming the samples in the source files.":"自动类别适用于同一根名称下所有带日期或大小写不同的写法。无需修改源文件中的样品名称即可调整。",
  "Reset automatic categories":"恢复自动类别",
  "Runs, QC and forensic log":"运行、质控与追溯日志",
  "One row per run, followed by a traceable log of structural findings, provenance and instrument-versus-name disagreements.":"每次运行一行，并附有结构性发现、来源及仪器类型与名称不一致情况的可追溯日志。",
  "Download runs and forensic log (CSV)":"下载运行与追溯日志（CSV）",
  "Raw fluorescence as stored in the AcquisitionStore, with no smoothing and no baseline subtraction. Controls are drawn over ordinary samples so they stay visible.":"显示 AcquisitionStore 中保存的原始荧光数据，不进行平滑或基线扣除。对照曲线绘制在普通样品之上，便于查看。",
  "Sample":"样品","Log fluorescence axis":"荧光轴使用对数刻度",
  "Download curves (CSV)":"下载扩增曲线（CSV）","Save chart as PNG":"将图表保存为 PNG",
  "Run metadata, thermal program, detection channels, subsets, analysis objects, standard curves and the instrument's own replicate statistics, decoded verbatim from the file.":"逐项解码文件中的运行元数据、温度程序、检测通道、子集、分析对象、标准曲线及仪器自身的重复孔统计。",
  "Download instrument records (ZIP)":"下载仪器记录（ZIP）",
  "Download English website (ZIP)":"下载英文网站（ZIP）","Download Chinese website (ZIP)":"下载中文网站（ZIP）",
  "Download":"下载","Nothing loaded yet.":"尚未加载数据。",
  "Load one or more .ixo experiments to use this sheet.":"请加载一个或多个 .ixo 实验以使用此页面。",
  "All analyses":"全部分析","Target":"目标","Analysis":"分析","Difference":"差值","Review":"审核",
  "within highlight threshold":"未超过突出显示阈值",
  "Results":"结果","Amplified":"已扩增","Mean Cq":"平均 Cq","Median":"中位数","Min":"最小值",
  "Max":"最大值","Uncertain":"不确定","No curve":"无曲线","Range":"范围","Finding":"发现",
  "Wells":"孔位","Well":"孔位","Replicates":"重复孔","Run mean Cq":"运行平均 Cq",
  "Date":"日期","Series":"系列","Runs":"运行次数","Mean / SD":"均值 / 标准差","Assessment":"评估",
  "not estimated as control limits":"未估算为控制限","not detected":"未检出",
  "no Westgard flag":"无 Westgard 标记",
  "fewer than three numeric run points — limits not drawn":"少于 3 个有效运行点，未绘制控制限",
  "Root name":"根名称","Names found":"发现的名称","Automatic category":"自动类别","Use as":"设为",
  "Calibrator":"校准品","Positive calibrator":"阳性校准品","Negative calibrator":"阴性校准品",
  "Standard":"标准品","Positive control":"阳性对照","Negative control":"阴性对照",
  "No-template control":"无模板对照","No template control":"无模板对照","Extraction blank":"提取空白",
  "Blank":"空白","Internal control":"内部对照","Inhibition control":"抑制对照","LOD control":"检出限对照",
  "Spike":"加标样品","External reference":"外部参照","Other control":"其他对照",
  "Ignore / not a control":"忽略 / 非对照","Unknown":"未知","Reference":"参照",
  "Run metadata":"运行元数据","Thermal program":"温度程序","Detection channels":"检测通道",
  "Subsets":"子集","Analysis objects":"分析对象","Instrument replicate statistics":"仪器重复孔统计",
  "Field":"字段","Stored value":"保存值","No record of this type.":"无此类记录。",
  "Forensic log":"追溯日志","Operator":"操作员","Instrument":"仪器","Plate":"板",
  "Analyses":"分析","Curves":"曲线","Errors":"错误","Status":"状态","Level":"级别","Area":"区域",
  "Evidence":"证据","Error":"错误","information":"信息","review":"审核","error":"错误",
  "Recovery":"数据恢复","Experiment decoded":"实验已解码","Channel assignment":"通道分配",
  "Curve linkage":"曲线关联","Sample role":"样品角色","Detection format":"检测格式",
  "Assay controls":"检测对照","Melting curve":"熔解曲线",
  "Analysis membership":"分析归属","QC":"质控","Fluorescence could not be decoded":"无法解码荧光数据",
  "Duplicate result records":"重复结果记录","Cq remains available":"Cq 仍可用",
  "No structural review finding":"未发现结构性审核问题",
  "The run may still require assay-specific acceptance review":"本次运行仍可能需要按检测方法进行接收审核",
  "Named position with a rising curve is in no analysis":"带上升曲线的已命名孔位未纳入任何分析",
  "Rising curve is in no analysis":"上升曲线未纳入任何分析",
  "No structural finding":"无结构性发现","Review findings are available":"存在审核发现",
  "Structural errors found":"发现结构性错误","No structural finding in the loaded data":"加载的数据中未发现结构性问题",
  "These checks describe recoverability and internal consistency; they do not replace method-specific acceptance.":"这些检查用于说明数据可恢复性和内部一致性，不能替代方法特定的接收标准。",
  "Download review tables (ZIP)":"下载审核表（ZIP）",
  "experiments loaded":"已加载实验","stored quantification rows":"保存的定量记录",
  "linked amplification curves":"已关联的扩增曲线","structural errors":"结构性错误",
  "review findings":"审核发现","uncertain stored calls":"不确定的保存判定",
  "rising curves omitted from analyses":"未纳入分析的上升曲线",
  "analysis summaries":"分析汇总","result rows without a linked curve":"未关联曲线的结果记录",
  "Replicate groups to review":"需审核的重复孔组","Signal vs median":"相对中位数信号",
  "curves drawn":"已绘制曲线","maximum cycles":"最大循环数","control-role curves":"对照角色曲线",
  "Flagged curves omitted from analyses":"已标记且未纳入分析的曲线",
  "Flagged curve omitted from analyses":"已标记且未纳入分析的曲线",
  "Omitted from analyses":"未纳入分析","Not analysed":"未分析",
  "The CSV contains every cycle of every selected curve, including curves hidden by overlap in the chart.":"CSV 包含每条已选曲线的全部循环数据，包括图中因重叠而不可见的曲线。",
  "No decoded amplification curves match this selection.":"没有与当前选择匹配的已解码扩增曲线。",
  "Cycle":"循环","Raw fluorescence":"原始荧光","Fluorescence (log scale)":"荧光（对数刻度）",
  "Experiment date (day.month)":"实验日期（日.月）","No numeric Cq in this series":"此系列无有效 Cq",
  "Rows":"行数","With a stored Cq":"含保存 Cq","With a stored concentration":"含保存浓度",
  "With a decoded curve":"含已解码曲线","Melting peaks":"熔解峰","Concentration":"浓度","Call":"判定结果",
  "Setting":"设置","Value":"值","Read from":"读取来源","Analysis modules":"分析模块",
  "Absolute Quantification":"绝对定量","Relative Quantification":"相对定量",
  "Tm Calling":"熔解温度调用","Endpoint Genotyping":"终点法基因分型","Melting Curve Genotyping":"熔解曲线基因分型",
  "Declared but not acquired":"已声明但未采集","Study result":"研究结果","Crossing Point":"交叉点",
  "Melting temperature":"熔解温度","Genotype":"基因型","Cycles acquired":"采集循环数",
  "Stored results":"保存的结果","Sample roles":"样品角色","Target / reference roles":"目标 / 参照角色",
  "Declared targets":"已声明目标","Endogenous reference":"内源参照","Target names":"目标名称",
  "Standard curves":"标准曲线","Stored efficiencies":"保存的扩增效率","Study columns":"研究列",
  "Colour compensation":"颜色补偿","Run created":"运行创建时间","Last modified":"最后修改时间",
  "Last modified by":"最后修改者","Serial number":"序列号","Container":"容器","Plate positions":"板孔位置",
  "Cq values (CSV)":"Cq 数值（CSV）","RDES table (TSV)":"RDES 表（TSV）",
  "RDML 1.4 — for LinRegPCR":"RDML 1.4 - 用于 LinRegPCR","qpcR curve table (CSV, wide)":"qpcR 曲线表（CSV，宽格式）",
  "Experiment settings (CSV)":"实验设置（CSV）","Everything, as one ZIP":"全部内容打包为 ZIP",
  "Every stored crossing point with its well, sample, target, role and call. The plain table most downstream work starts from.":"包含每个保存的交叉点及其孔位、样品、目标、角色和判定结果，是大多数后续分析的基础表格。",
  "Stored Cq beside the full amplification curve, one row per cycle. The long-format table for scripts that expect tidy data.":"将保存的 Cq 与完整扩增曲线并列，每个循环一行，适用于长格式数据脚本。",
  "Version 1.4 with every dye declared. rdmlpython refuses LinRegPCR below 1.4, and raises KeyError on a target whose dye was never declared; both were checked by running it.":"采用 RDML 1.4 并声明所有染料；已通过实际运行验证 rdmlpython / LinRegPCR 的兼容性。",
  "One column per well, first column named Cycles exactly as pcrbatch() demands. Column names carry target and sample so replicate groups form with one sub().":"每个孔位一列，首列按 pcrbatch() 要求命名为 Cycles；列名包含目标和样品，便于构建重复孔组。",
  "Melting temperature, peak area and peak height for every well, as the Tm Calling analysis stored them. Only runs that carry such an analysis produce this.":"包含 Tm Calling 分析保存的每孔熔解温度、峰面积和峰高，仅对含此类分析的运行提供。",
  "Every setting the page could read out of the container, each with the property it came from. The same table shown on the Load tab.":"列出页面从容器读取的全部设置及其来源属性，与“加载”页显示的表格相同。",
  "Every table above plus both scripts, so a whole experiment can be handed over in a single file.":"包含上述所有表格和两个脚本，可用单个文件交付完整实验。",
  "Download R script":"下载 R 脚本","Download Python script":"下载 Python 脚本",
  "Showing pasted Cq values. Load an .ixo file for the full table.":"当前显示粘贴的 Cq 值；加载 .ixo 文件可查看完整表格。",
  "Automatic":"自动","mean":"均值","none":"无","none declared":"未声明","not declared":"未声明",
  "applied":"已应用","not applied":"未应用","decoded":"已解码","quantification":"定量",
  "melting":"熔解","genotyping":"基因分型","relative quantification":"相对定量","Unassigned":"未分配",
  "instrument groups":"仪器分组","identical sample names":"相同样品名称",
  "none — every well is left Unknown":"无 - 所有孔位均保留为未知",
  "file(s) staged:":"个文件已暂存：","Nothing usable was selected.":"未选择可用文件。",
  "Nothing could be read.":"无法读取任何文件。"
};
