function edsRecordTables(run){
  const p=run&&run.eds;if(!p)return {};
  const A=p.analysis,L=p.log;
  return {
    calibrations:p.calibrations.map(c=>({file:c.file,calibration:c.name,id:c.id,performed:EDS.dt(c.ts),expires:EDS.dt(c.exp),
      status_on_run_date:c.exp&&p.exp.runStart&&c.exp<p.exp.runStart?"expired":"valid",operator:c.operator,version:c.version})),
    software_modules:p.tools.map(t=>({module:t.name,version:t.version,id:t.id})),
    target_settings:Object.entries(A.detectors).map(([t,d])=>({target:t,reporter:(p.exp.detectors.find(x=>x.name===t)||{}).reporter||"",
      quencher:(p.exp.detectors.find(x=>x.name===t)||{}).quencher||"",threshold:d.threshold,automatic_threshold:d.autoCt,
      automatic_baseline:d.autoBaseline,baseline_start:d.bStart,baseline_end:d.bStop,confidence:d.confidence})),
    analysis_settings:[...Object.entries(A.ddct).map(([k,v])=>({setting:k,value:v,source:"IDDCtAnalysisSettings"})),
      {setting:"SignalSmoothing",value:String(A.smoothing),source:"ISignalSmoothingSettings"},
      {setting:"Algorithm",value:A.algorithm,source:"IAlgorithmSelectSettings"},
      ...Object.entries(A.dataSelect).map(([k,v])=>({setting:k,value:v,source:"IDataSelectSettings"}))],
    flag_rules:A.rules.map(r=>({code:r.code,name:EDS.flagName(r.code),description:(EDS.FLAGS[r.code]||[])[1]||"",
      name_confirmed:(EDS.FLAGS[r.code]||[])[2]?"yes":"inferred",criteria:r.criteria,enabled:r.enabled,auto_omit:r.omitEnabled,
      wells_flagged:p.plate.wells.filter(w=>w.flags.some(f=>f.code===r.code)).map(w=>w.pos).join(" ")})),
    std_curves:Object.values(p.stdCurves||{}).map(sc=>({target:sc.target,slope:sc.slope,y_intercept:sc.yIntercept,r2:sc.r2,
      efficiency_percent_derived:sc.efficiency!=null?Number(sc.efficiency.toFixed(4)):"",unlabelled_field_4:sc.field4,unlabelled_field_6:sc.field6,
      points:sc.x?sc.x.length:"",log10_quantity:(sc.x||[]).join(" "),ct:(sc.y||[]).join(" ")})),
    provenance:[{field:"experiment id",value:p.exp.experimentId||""},{field:"run name in messages.log",value:(p.log||{}).runName||""},
      {field:"run folders named in quant/*.xml",value:((p.provenance||{}).quantRunNames||[]).join(", ")},
      {field:"original path (experiment.xml FileName)",value:p.exp.fileName},
      {field:"plate_setup.ini dyes / reference",value:(p.provenance||{}).plateIni?`${p.provenance.plateIni.dyes.join(", ")} / ${p.provenance.plateIni.reference}`:""},
      ...(((p.provenance||{}).exportSetting)?[{field:"last export format",value:p.provenance.exportSetting.format},
        {field:"last export location",value:p.provenance.exportSetting.location},{field:"last export file name",value:p.provenance.exportSetting.fileName}]:[])],
    export_settings:(((p.provenance||{}).exportSetting||{}).sets||[]).map(x=>({section:x.title,type:x.type,omitted:x.omit,skip_empty_wells:x.skipEmpty,columns:x.cols.join(" | ")})),
    well_baselines:p.results.filter(x=>x.baseline).map(x=>({well:x.pos,sample:x.sample,target:x.target,automatic:x.baseline.auto,start:x.baseline.start,end:x.baseline.stop})),
    integrity:[{check:"ZIP CRC-32",result:p.crcOk?"all entries valid":"failed: "+p.crcBad.join(", ")},
      {check:"Tamper (stored)",result:p.tamper.stored},{check:"Tamper (recomputed)",result:p.tamper.computed},
      {check:"Tamper verdict",result:p.tamper.ok===true?"matches":p.tamper.ok===false?"MISMATCH":"no record"},
      {check:"SHA-256 of the file",result:p.sha256},{check:"Archive entries",result:p.entries.length}],
    archive_entries:p.entries.map(x=>({entry:x.name,bytes:x.usize,compressed:x.csize,zip_date:x.date,
      crc32:x.crc.toString(16).padStart(8,"0"),crc_valid:x.dir?"":(x.crcOk?"yes":"NO")})),
    log_summary:L?[{field:"started",value:EDS.dt(L.start)},{field:"ended",value:EDS.dt(L.end)},
      {field:"firmware",value:L.version},{field:"product",value:L.props.product||""},{field:"host",value:L.props.hostname||""},
      {field:"temperature_records",value:L.temps.length},{field:"images",value:L.images},
      {field:"max_zone_spread_C",value:L.temps.length?Math.max(...L.temps.map(t=>t[4])).toFixed(2):""},
      {field:"led_junction_C",value:L.leds.length?`${Math.min(...L.leds.map(x=>x[4])).toFixed(1)} – ${Math.max(...L.leds.map(x=>x[4])).toFixed(1)}`:""},
      ...Object.entries(L.counts).map(([k,v])=>({field:"records_"+k,value:v}))]:[],
    log_events:L?L.events.map(e=>({time:EDS.dt(e[0]),event:e[1]})):[],
    log_errors:L?L.errors.map(e=>({time:EDS.dt(e[0]),level:e[1],message:e[2]})):[],
    temperature_trace:L?L.temps.map(t=>({time:EDS.dt(t[0]),minutes:((t[0]-L.temps[0][0])/60000).toFixed(3),
      sample_mean_C:t[1],cover_C:t[2],heatsink_C:t[3],zone_spread_C:t[4]})):[]
  };
}
