const CC_CHARTS=[
 /* ---------------- 1. HARDWARE ---------------- */
 {id:"heat_rate",code:"B-H1",group:"hardware",inst:["LC","QS"],type:"trend",unit:"°C/s",better:"high",spec:{LC:{lo:4.3},QS:{}},
  title:"Peak heating rate (2-s window)",source:"LC TemperatureLog · QS log sample temperature",
  idea:"How fast the Peltier elements can heat the block: the steepest 2-second slope of every heating transition, median over the run (manual: 4.8 °C/s). Independent of plateau detection, so short holds do not distort it.",
  reading:"A slow fall over months is Peltier or thermal-interface ageing; the fitted line gives a conditional limit-crossing estimate, not a failure date. A single low run points to the plate or a blocked vent that day."},
 {id:"cool_rate",code:"B-H2",group:"hardware",inst:["LC","QS"],type:"trend",unit:"°C/s",better:"high",spec:{LC:{lo:2.1},QS:{}},
  title:"Peak cooling rate (2-s window)",source:"as B-H1",
  idea:"How well the heat sink and fans remove heat: steepest 2-second cooling slope of every transition, median over the run (manual: 2.5 °C/s).",
  reading:"Falling cooling with stable heating = clogged fan filter or failing fan (clean the filters, check fans) before Peltier replacement."},
 {id:"overshoot",code:"B-H3",group:"hardware",inst:["LC","QS"],type:"cusum",unit:"°C",better:"target",
  title:"Overshoot at the denaturation step",source:"as B-H1",
  idea:"Block temperature beyond the setpoint before it settles. The LC480 overshoots 4–6 °C by design, identically every cycle.",
  reading:"Watch for change, not size: a CUSUM drifting up or down means the controller or the temperature sensor has changed."},
 {id:"settling",code:"B-H3b",group:"hardware",inst:["LC","QS"],type:"i",unit:"s",better:"low",res:{LC:0.41,QS:1},
  title:"Settling time at the denaturation step",source:"as B-H1",
  idea:"Seconds from the 90 % point until the block stays within ±0.5 °C of the setpoint.",
  reading:"Longer settling with a normal ramp rate points to control tuning or sensor lag."},
 {id:"transition",code:"B-H3c",group:"hardware",inst:["LC","QS"],type:"i",unit:"s",better:"low",variants:true,res:{LC:0.1,QS:0.5},
  title:"Transition time A → B °C",source:"LC TemperatureLog · QS log sample temperature · run program",
  idea:"Seconds the block needs to go from one programmed temperature to the next (e.g. 95 → 60 °C): from leaving ±0.5 °C of the start temperature until first within ±0.5 °C of the target, median over all cycles of the run. One chart per transition of the program. Includes ramp and overshoot, so it shows how much of every cycle is spent moving instead of holding.",
  reading:"Compare a transition only with itself and the same program. A cooling transition that lengthens while heating transitions stay flat points to heat removal (fans, filters, heat sink); all transitions lengthening together points to the Peltier elements or the room."},
 {id:"hold_temp",code:"B-H4",group:"hardware",inst:["LC","QS"],type:"xbars",unit:"°C from setpoint",better:"target",
  title:"Temperature at the moment of reading",source:"LC temperature of every acquisition · QS sample temperature of every image",
  idea:"Offset (X̄) and stability (S) of the block while the camera reads, one subgroup per run.",
  reading:"X̄ drifting away from its usual offset = temperature calibration drift (verify with a temperature plate). S rising = unstable control."},
 {id:"zone_spread",code:"B-H5",group:"hardware",inst:["QS"],type:"ewma",unit:"°C",better:"low",spec:{QS:{hi:1.5}},
  title:"Block zone uniformity (95th percentile)",source:"QS log, six sample zones",
  idea:"Difference between the warmest and coolest of the six zones, 95th percentile over the run.",
  reading:"An EWMA creeping up means one zone is losing its match; look at the Temperature graph to find which."},
 {id:"heatsink_max",code:"B-H6",group:"hardware",inst:["QS"],type:"i",unit:"°C",better:"low",
  title:"Heat-sink maximum",source:"QS log",idea:"Highest heat-sink temperature during the run.",
  reading:"Rising over time with the same protocol = cooling capacity dropping (fans, dust, room temperature)."},
 {id:"cover_temp",code:"B-H6b",group:"hardware",inst:["QS"],type:"i",unit:"°C",better:"target",
  title:"Heated cover temperature",source:"QS log",idea:"Median cover temperature during the run (setpoint 105 °C).",
  reading:"Below the setpoint = cover heater fault; condensation and evaporation follow."},
 {id:"lamp_ref",code:"B-H8",group:"hardware",inst:["LC"],type:"i",unit:"reference counts",better:"target",variants:true,
  title:"Lamp reference channel (stability)",source:"LC AcquisitionStore RefValue, first reading of the run, per filter pair",
  idea:"The instrument measures the Xenon lamp through a reference channel and compensates for it. In 155 runs from 2022–2026 the value stayed within ±1 %, so it shows regulation, not lamp ageing. Lamp hours and intensity % are only in Tools → Instruments (manual p. 208).",
  reading:"Stable = the lamp is still inside the range the instrument can compensate. A step or a point outside the limits = lamp, light guide or reference-sensor fault; check the lamp intensity % in the instrument software."},
 {id:"lamp_drift",code:"B-H9",group:"hardware",inst:["LC"],type:"i",unit:"% change in the run",better:"target",variants:true,
  title:"Lamp drift within a run",source:"LC RefValue first vs last reading",
  idea:"How much the lamp intensity changes during one run.",reading:"Growing drift is typical of a lamp near the end of its life."},
 {id:"led_current",code:"B-H10",group:"hardware",inst:["QS"],type:"trend",unit:"current (as logged)",better:"target",
  title:"LED drive current",source:"QS log LEDStatus",idea:"Median LED current during the run.",
  reading:"The instrument raises current to keep light output: a rising trend is LED ageing; the line predicts when it reaches the limit you set."},
 {id:"led_junction",code:"B-H10b",group:"hardware",inst:["QS"],type:"i",unit:"°C",better:"low",
  title:"LED junction temperature (maximum)",source:"QS log LEDStatus",idea:"Hottest LED junction temperature in the run.",
  reading:"Higher than usual = LED cooling problem; LEDs age faster when hot."},
 {id:"exposure",code:"B-H11",group:"hardware",inst:["LC","QS"],type:"i",unit:"ms",better:"low",variants:true,
  title:"Automatic integration time / exposure",source:"LC IntgrTime per channel · QS exposure per filter",
  idea:"Both instruments lengthen exposure automatically when the signal is weak.",
  reading:"A slow rise is compatible with weaker signal; verify matched controls and optical configuration before attributing ageing (compare with B-H8/B-H10); a jump after a reagent change points to the method instead."},
 {id:"saturation",code:"B-H12",group:"hardware",inst:["QS"],type:"p",unit:"share of well images",better:"low",
  title:"Saturated well images",source:"QS quant files, saturation column",idea:"Share of well images with at least one saturated pixel.",
  reading:"A rise = exposure logic or camera fault, or overloaded samples; values above zero make the curve plateau unreliable."},
 {id:"calib_uniformity",code:"B-H13",group:"hardware",inst:["QS"],type:"i",unit:"edge / centre",better:"target",
  title:"Uniformity calibration: edge-to-centre ratio",source:"QS calibrations/uniformity.ini",
  idea:"Changes only when the instrument is recalibrated.",reading:"A step at a recalibration shows how much the optics changed; a large step deserves a service question."},
 {id:"calib_background",code:"B-H13b",group:"hardware",inst:["QS"],type:"i",unit:"counts",better:"low",
  title:"Background calibration: mean offset",source:"QS calibrations/background.ini",idea:"Mean absolute background offset of the last background calibration.",
  reading:"Rising between calibrations = contamination of the block or optics."},
 {id:"calib_roi",code:"B-H13c",group:"hardware",inst:["QS"],type:"i",unit:"pixels",better:"target",
  title:"Well-position (ROI) calibration: spot diameter",source:"QS calibrations/roi.ini",idea:"Mean spot diameter from the ROI calibration.",
  reading:"A change means the optical alignment moved."},
 {id:"wheel_ms",code:"B-H14",group:"hardware",inst:["QS"],type:"i",unit:"ms",better:"low",
  title:"Filter-wheel move time",source:"QS log Motor start/end",idea:"Median time of a filter-wheel move.",
  reading:"Slower moves = motor or bearing wear."},
 {id:"wheel_slow",code:"B-H14b",group:"hardware",inst:["QS"],type:"p",unit:"share of moves",better:"low",
  title:"Filter-wheel moves slower than 500 ms",source:"QS log",idea:"Share of moves longer than 500 ms (normal ≈ 300 ms).",
  reading:"Occasional stalls come before a failure; any upward trend is worth a service call."},
 {id:"encoder",code:"B-H15",group:"hardware",inst:["QS"],type:"i",unit:"encoder counts",better:"target",variants:true,
  title:"Filter-wheel position offset",source:"QS log Emission/Excitation Encoder",idea:"Encoder offset after each move; constant for a healthy wheel.",
  reading:"Any step = the wheel slipped, was re-homed or serviced."},
 {id:"cam_overhead",code:"B-H16",group:"hardware",inst:["QS"],type:"xbars",unit:"ms",better:"low",
  title:"Camera readout time beyond the exposure",source:"QS log CAMera start/end minus requested exposure",
  idea:"About 0.5 s per image; one subgroup = all images of the run.",reading:"A jump = camera or its interface; a slow rise = controller slowing (compare with software charts)."},
 {id:"chan_switch",code:"B-H17",group:"hardware",inst:["LC"],type:"i",unit:"ms",better:"low",res:{LC:10},
  title:"Channel switch time",source:"LC acquisition times minus integration time",
  idea:"Time between the channels of one reading, net of integration (≈ 1.0–1.4 s; filter switch < 0.65 s by the manual).",
  reading:"Rising = filter wheels or camera readout slowing."},
 {id:"cover_down",code:"B-H18",group:"hardware",inst:["QS"],type:"trend",unit:"s",better:"low",x:"cycles",
  title:"Heated cover lowering time",source:"QS log Cover Lowering → Lowered",idea:"Motorised cover pressing onto the plate (≈ 10 s).",
  reading:"Getting slower = motor or linkage wear, or plates/seals that are too tall."},
 {id:"cover_up",code:"B-H18b",group:"hardware",inst:["QS"],type:"i",unit:"s",better:"low",
  title:"Heated cover raising time",source:"QS log Cover Raising → Raised",idea:"Cover lifting off the plate (≈ 5.4 s).",reading:"As B-H18."},
 {id:"bg_median",code:"A-H3",group:"hardware",inst:["LC","QS"],type:"i",unit:"fluorescence",better:"target",variants:true,
  title:"Background fluorescence per channel",source:"stored curves, cycles 3–10",idea:"Median background of all wells, per channel.",
  reading:"Slow decline = light source ageing; a raised run = plate, seal or contamination."},
 {id:"plateau_median",code:"A-H3b",group:"hardware",inst:["LC","QS"],type:"i",unit:"fluorescence",better:"target",variants:true,
  title:"End-point fluorescence per channel",source:"stored curves, last cycle",idea:"Median end-point of all wells, per channel.",
  reading:"Moves together with B-H8/B-H10 when optics age; alone it points to the method (probe) — see M-group."},
 {id:"run_minutes",code:"A-H4",group:"hardware",inst:["LC","QS"],type:"i",unit:"minutes",better:"target",
  title:"Run duration",source:"run start / end",idea:"Only comparable between runs of the same protocol.",
  reading:"A much shorter or longer run with the same protocol = aborted, paused or held run."},
 /* ---------------- 2. SOFTWARE ---------------- */
 {id:"cmd_rt",code:"B-S1",group:"software",inst:["QS"],type:"i",unit:"ms (95th pct)",better:"low",log:true,
  title:"Reply time to the PC software",source:"QS log C: → S: pairs",idea:"How fast the embedded computer answers commands.",
  reading:"Rising = controller overloaded or network problem."},
 {id:"tick_late",code:"B-S2",group:"software",inst:["QS"],type:"i",unit:"ms (95th pct)",better:"low",
  title:"Once-per-second timer lateness",source:"QS log Time lines",idea:"How late the 1-s housekeeping timer fires.",
  reading:"Rising = the embedded CPU is saturated (mostly while imaging)."},
 {id:"catch_up",code:"B-S2b",group:"software",inst:["QS"],type:"u",unit:"events per run hour",better:"low",
  title:"Scheduler falling behind",source:"QS log Scheduler 'Catching up'",idea:"How often the task scheduler had to catch up, per hour of run.",
  reading:"A u-chart above its limit = the internal computer is overloaded."},
 {id:"img_proc",code:"B-S3",group:"software",inst:["QS"],type:"i",unit:"ms (95th pct)",better:"low",log:true,
  title:"Image → processing delay",source:"QS log Image → Preprocessing",idea:"Time from the last image to the start of its processing.",
  reading:"Rising = storage or CPU slowing; one long delay is a single stall."},
 {id:"roi_ms",code:"B-S4",group:"software",inst:["QS"],type:"i",unit:"ms",better:"low",
  title:"Image analysis time",source:"QS log ROI Quantitation",idea:"The software's own processing time per image.",
  reading:"A step after an update = different firmware behaviour (see version markers)."},
 {id:"runtime_err",code:"B-S5",group:"software",inst:["QS"],type:"i",unit:"%",better:"target",
  title:"Run-time prediction error",source:"QS log Time elapsed/remaining",idea:"Actual minus predicted run time.",
  reading:"Creeping up = actions take longer than the firmware expects."},
 {id:"handoff_min",code:"B-S6",group:"software",inst:["QS"],type:"i",unit:"minutes",better:"low",
  title:"Data hand-off time",source:"QS log end → instrumentdata.mf time",idea:"Minutes from run end until the data were packed for the PC.",
  reading:"Long = network or PC problem, or a manual delay."},
 {id:"log_errors",code:"B-S8",group:"software",inst:["QS"],type:"c",unit:"errors",better:"low",
  title:"Command errors in the instrument log",source:"QS log 'Error in command'",idea:"Count of command errors per run.",
  reading:"New or more errors = firmware or configuration change."},
 {id:"cycle_sd",code:"B-S9",group:"software",inst:["LC","QS"],type:"i",unit:"ms",better:"low",
  title:"Cycle-timing regularity",source:"LC acquisition times · QS image times",idea:"Standard deviation of the cycle period within a run.",
  reading:"Larger = scheduling problems in the instrument."},
 {id:"templog_late",code:"B-S10",group:"software",inst:["LC"],type:"p",unit:"share of intervals",better:"low",
  title:"Temperature-log intervals over 500 ms",source:"LC TemperatureLog times (normally 410–420 ms)",idea:"Regularity of the control-loop logging.",
  reading:"Any rise = controller overload."},
 {id:"invalid_acq",code:"B-S11",group:"software",inst:["LC"],type:"p",unit:"share of readings",better:"low",
  title:"Invalid fluorescence readings",source:"LC AcquisitionStore Valid flag",idea:"Readings the instrument marked invalid.",reading:"Above zero = acquisition fault."},
 {id:"ct_mismatch",code:"B-S12",group:"software",inst:["QS"],type:"p",unit:"share of wells",better:"low",
  title:"Stored Ct not reproducible (> 0.2)",source:"stored ΔRn and threshold",idea:"Wells whose stored Ct differs from the recalculation.",
  reading:"Non-zero requires checking algorithm, precision, stored settings and provenance; it does not establish post-analysis editing."},
 {id:"edit_delay",code:"A-S4",group:"software",inst:["LC","QS"],type:"i",unit:"log10 hours",better:"low",
  title:"Run end → last change",source:"file dates",idea:"Processing delay on a log scale (0 = 1 h, 1 = 10 h, 2 = 100 h).",
  reading:"Points above the limit are late edits; cross-check with the operator group."},
 {id:"findings",code:"A-S6",group:"software",inst:["LC","QS"],type:"c",unit:"findings",better:"low",
  title:"Forensic findings per run",source:"forensic log (review + error)",idea:"Count of review and error findings for the run.",
  reading:"A run above the limit needs a closer look in the forensic log."},
 /* ---------------- 3. METHOD ---------------- */
 {id:"pc_cq",segmentBy:"batch",code:"A-M1",group:"method",inst:["LC","QS"],type:"i",unit:"Cq",better:"target",variants:true,westgard:true,
  title:"Positive control Cq (Levey-Jennings)",source:"SOP positive-control wells",idea:"Mean Cq of the positive control per run and target, with Westgard rules.",
  reading:"Across-run rules flag unexpected control behaviour. R-4s is not applied to run means. Investigate lot, extraction batch, assay and instrument effects."},
 {id:"pc_amplitude",segmentBy:"batch",code:"B-M1",group:"method",inst:["LC","QS"],type:"ewma",unit:"fluorescence",better:"high",variants:true,
  title:"Probe signal strength (positive control)",source:"stored curves of the positive control",idea:"Amplitude (plateau above background) of the same control each run.",
  reading:"Falling with a stable Cq = probe or dye degradation (storage, freeze-thaw); a step at a lot change = the lot. Compare with B-H8/B-H10 to exclude the optics."},
 {id:"rox_level",code:"B-M2",group:"method",inst:["QS"],type:"i",unit:"passive reference",better:"target",
  title:"Passive reference (ROX) level",source:"QS multicomponent data, cycles 1–5",idea:"Median passive-reference level of named wells.",
  reading:"A step = new master-mix lot or ROX concentration."},
 {id:"efficiency",code:"B-M3",group:"method",inst:["LC","QS"],type:"trend",unit:"% efficiency",better:"target",variants:true,spec:{LC:{lo:90,hi:110},QS:{lo:90,hi:110}},
  title:"PCR efficiency from the standards",source:"standards with a stored quantity",idea:"Efficiency of the standard curve per run and target.",
  reading:"A slow drop = degrading standard or reagent; outside 90–110 % fails MIQE-style acceptance."},
 {id:"ntc_rate",code:"B-M5",group:"method",inst:["LC","QS"],type:"p",variants:true,unit:"share of NTC wells",better:"low",
  title:"Negative controls by process stage",source:"SOP negative controls",idea:"Share of negative-control wells with any Cq.",
  reading:"Rising = contamination of reagents or of the working area (ISFG, MIQE)."},
 {id:"ic_shift",code:"B-M6",group:"method",inst:["LC","QS"],type:"ewma",unit:"cycles",better:"low",
  title:"IC shift from fixed reference",source:"SOP internal-control target",idea:"Mean IC Cq shift from the configured fixed reference. Missing reference means unavailable; endogenous taxon targets are not fixed-input IPCs.",
  reading:"Upward drift = extraction method or kit problem."},
 {id:"low_conf",code:"B-M9",group:"method",inst:["QS"],type:"p",unit:"share of wells",better:"low",
  title:"Low Cq confidence",source:"QS CQCONF flag",idea:"Share of wells flagged for low Cq confidence.",reading:"A rise = noisy curves, often probe or baseline problems."},
 {id:"late_rate",code:"B-M10",group:"method",inst:["LC","QS"],type:"p",unit:"share of results",better:"low",
  title:"Late signal / stochastic-zone results",source:"SOP outcomes",idea:"Share of sample results falling in the late-signal or low-quantity zone.",
  reading:"A rise = sensitivity drop or poorer samples."},
 /* ---------------- 4. OPERATOR ---------------- */
 {id:"rep_sd",code:"B-O1",group:"operator",inst:["LC","QS"],type:"i",unit:"Cq SD",better:"low",byOperator:true,
  title:"Replicate precision (pooled SD, Cq < 30)",source:"replicate groups",idea:"Pipetting precision; replicates above Cq 30 are left out so stochastic noise does not hide skill.",
  reading:"One operator's points above the others → retraining; everyone rising → pipette calibration."},
 {id:"rox_cv",code:"B-O2",group:"operator",inst:["QS"],type:"i",unit:"% CV",better:"low",byOperator:true,
  title:"Dispensed-volume spread (ROX CV)",source:"QS passive reference, cycles 1–5",idea:"Raw passive-reference level varies with the dispensed volume.",
  reading:"High CV = uneven pipetting or bubbles."},
 {id:"rowcol",code:"B-O3",group:"operator",inst:["LC","QS"],type:"i",unit:"Cq",better:"low",byOperator:true,
  title:"Row / column pattern",source:"replicate residuals by plate row and column",idea:"Largest mean Cq offset of a plate row or column.",
  reading:"One row or column off = a faulty multichannel tip or loading-order error."},
 {id:"ntc_op",code:"B-O5",group:"operator",inst:["LC","QS"],type:"funnel",metric:"ntc_rate",variants:true,unit:"share of NTC wells",better:"low",
  title:"Contamination rate by operator (funnel)",source:"as B-M5",idea:"NTC positives per operator against the number of NTCs they ran.",
  reading:"Outside the 99.8 % line → investigate; the funnel keeps small workloads from looking unfair."},
 {id:"action_op",code:"B-O6",group:"operator",inst:["LC","QS"],type:"funnel",metric:"action_rate",unit:"share of results",better:"low",
  title:"Repeat / inconclusive / invalid rate by operator (funnel)",source:"SOP outcomes",idea:"Analytical robustness per person.",reading:"As B-O5."},
 {id:"manual_rate",code:"B-O7",group:"operator",inst:["LC","QS"],type:"p",unit:"share of settings",better:"low",byOperator:true,
  title:"Manual interventions",source:"manual threshold/baseline, omitted wells, manual calls",idea:"Share of settings or wells changed by hand.",
  reading:"High or rising → ask for documented reasons (OIG report lessons); compare operators with the funnel view."},
 {id:"call_disagree",code:"B-O9",group:"operator",inst:["LC","QS"],type:"p",unit:"share of wells",better:"low",byOperator:true,
  title:"Stored calls that disagree with the SOP",source:"stored call vs SOP outcome",idea:"Consistency and fairness: do calls follow the written rules?",
  reading:"Disagreement concentrated in one person or case type → training or bias check."},
 {id:"copied",code:"B-O11",group:"operator",inst:["LC","QS"],type:"c",unit:"events",better:"low",
  title:"Copied-data events",source:"forensic log (identical curves / Cq)",idea:"Must be zero.",reading:"Any event is a forensic finding."},
];
